### ISSUE TITLE
LSTM

### ISSUE THREAD

**Issue by MuyuXiaoxiang** [google/TensorNetwork#103]
Dear Sir,
         I want to use TensorFlow and LSTM to perform regression prediction on time series data and accelerate it to reduce the time. However I am not familiar with TensorNetwork, could I use it to implement what I need? If it is ok, what should I do to implement it? Thank you!

**Comment by Thenerdstation** [comment]
No, TensorNetwork can't be used to make an LSTM.

There are lots of resources online for how to make an LSTM in tensorflow. https://www.tensorflow.org/tutorials/sequences/recurrent

**Comment by MuyuXiaoxiang** [comment]
> No, TensorNetwork can't be used to make an LSTM.
> 
> There are lots of resources online for how to make an LSTM in tensorflow. https://www.tensorflow.org/tutorials/sequences/recurrent

Sorry, sir.  Maybe my statement is not very clear . What I want to know is that whether I can use the TensorNetwork to accelerate the training of lstm in tensorflow. Thank you for your reply.

**Comment by Thenerdstation** [comment]
The answer is still no. This library is just a high level wrapper for tensorflow, so it won't be any faster than just using tensorflow itself. This library just makes creating/contracting TensorNetworks significantly easier and allows you to run on accelerated hardware like GPUs and TPUs without any code changes.

You maybe can replace the LSTM cell with a hidden TensorNetwork, but it won't be faster than just using normal LSTM cell. It also has never been tried before afaik, so it might not even work.

**Comment by MuyuXiaoxiang** [comment]
> The answer is still no. This library is just a high level wrapper for tensorflow, so it won't be any faster than just using tensorflow itself. This library just makes creating/contracting TensorNetworks significantly easier and allows you to run on accelerated hardware like GPUs and TPUs without any code changes.
> 
> You maybe can replace the LSTM cell with a hidden TensorNetwork, but it won't be faster than just using normal LSTM cell. It also has never been tried before afaik, so it might not even work.

Thank you very much.
