### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#110]
Currently, our readthedocs documentation is very lack luster. The formatting for some of the function docs looks pretty bad, and the layout for the sidebar needs improvement. We also need example code and some basic tutorials to help people get started (these can possibly be taken from the existing README).

**Comment by mganahl** [comment]
Also, there are some errors thats should be fixed. I‘go through the docs and fix them.

**Comment by shubham15gupta09** [comment]
I would like to contribute here . 
How can i edit it 
please help me as i am new to these things
