### ISSUE TITLE
Remove the Assert{In,True,Not,...} calls in tensornetwork_test

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#113]
We want to inline all of the `Assert*` calls in tensornetwork_test.

These are left over from when we transitioned from googletest to pytest. They cause the error messages to be not as nice as they could be. It's mostly just tedious work, though I'm sure someone could write a short vim command to get it done.

**Comment by kshithijiyer** [comment]
```
# TODO(chaseriley): Remove these and inline the asserts
def assertEqual(a, b):
  assert a == b


def assertNotIn(a, b):
  assert a not in b


def assertIn(a, b):
  assert a in b


def assertTrue(a):
  assert a is True


def assertFalse(a):
assert a is False
```

We just have to remove these functions right?

**Comment by Thenerdstation** [comment]
Remove them and inline all of the asserts in the tests below.

**Comment by kshithijiyer** [comment]
> Remove them and inline all of the asserts in the tests below.

You want me to remove all the asserts?
