### ISSUE TITLE
import ncon in experiments/MPS/*.py seems broken

### ISSUE THREAD

**Issue by refraction-ray** [google/TensorNetwork#114]
In current head of master, these `import ncon` statements in experiments/MPS/*.py seem to be broken possibly due to the change of filename from ncon to ncon_interface.  I also cannot see why using `sys.path.append("../")` instead of `sys.path.append("../../tensornetwork")` in these files.

There is also no *_test file in MPS dir. Pytest should report the issue if there is any test py.

**Comment by Thenerdstation** [comment]
Thanks running this code and for catching these!

Yeah, I'm not terribly surprised that is broken right now. The MPS was an intern project, and we merged what he had on his last day. (It was self contained, so we weren't too worried it would break anything.)

We'll get this cleaned up and fixed today.

**Comment by Thenerdstation** [comment]
Oh wait you mean the `MPS` not the `MPS_classifier` directory. That was written by the physicists at PI before we added the code review lockdown, so now I'm even less surprised that's broken. In either case we'll fix it.

**Comment by Thenerdstation** [comment]
@mganahl @amilsted Would you too be willing to help add unit tests to this code? This is also directly related to https://github.com/google/TensorNetwork/issues/40.

**Comment by mganahl** [comment]
@Thenerdstation I can add unit tests to the MPS module.

**Comment by Thenerdstation** [comment]
Thank you! I fixed the imports as best as I could tell, so now run them as modules.

`python -m experiments.MPS.DMRG`

**Comment by mganahl** [comment]
@Thenerdstation, I justed fetched the latest changes from master. It looks that the tensornetwork import is broken. It throws a `ModuleNotFoundError: No module named 'graphviz'`

**Comment by Thenerdstation** [comment]
You need to install graphviz

**Comment by Thenerdstation** [comment]
Which reminds me, we should add that to the requirements before we push our next release

**Comment by mganahl** [comment]
Lol, sorry I thought that was part of the library
