### ISSUE TITLE
RFC: Overload * or @ for Nodes

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#116]
I was wondering about convenient ways of manually specifying a contraction order in terms of node pairs. Now I'm thinking it would be cool to overload either the `*` or, perhaps better, the `@` operator for `Node` objects so that it carries out `contract_between()`, returning the result.

Here is an example:
```python
tn = TensorNetwork()
a = tn.add_node(a_tensor)
b = tn.add_node(b_tensor)
c = tn.add_node(c_tensor)

# assume tensors are matrices and set up `trace(a @ b @ c)`
tn.connect(a[1], b[0])
tn.connect(b[1], c[0])
tn.connect(c[1], a[0])

res = (a @ b) @ c  # equivalent to `res = tn.contract_between(tn.contract_between(a, b), c)`
```

This syntax is so much nicer than lots of `contract_between()`, mainly because one can plausibly make the contraction a one-liner and avoid having to keep track of intermediate nodes.

It would require `Node`s to know which network they belong to.

**Comment by mganahl** [comment]
:thumbsup:

**Comment by Thenerdstation** [comment]
That does feel nice.

I don't immediately see an issue with having node store it's parent network. There might be some headache when removing a node, but that seems minor. (And it would also force the node to only exist in only one network)

I'll add this tonight.
