### ISSUE TITLE
import tensornetwork error

### ISSUE THREAD

**Issue by clanglett85** [google/TensorNetwork#125]
Installed Docker and tensornetwork as instructed on the install page. When I go to a project in python I am unable to to get the tensornetwork framework to get recognized for use. Has anyone else had similar issues?

**Comment by Thenerdstation** [comment]
Hm strange. We don't have tests for the docker install so there could be an issue. Can you give us more information on the install error?

**Comment by clanglett85** [comment]
Gladly. So I previously already had tensorflow 2.0 beta installed for other projects, so I know this already works on my system. To install tensornetwork I followed the installation:
1.) pip3 install
2.)installed docker on my mac
3.) git clone and those steps
4.) go to jupyter notebook and try and example and I get 
      ModuleNotFoundError: No module named 'tensornetwork'
I also get this error message if I use a text-editor and build through the terminal.

**Comment by Thenerdstation** [comment]
That seems likely an issue with your docker setup.

We don't use docker internally, so it's a little difficult to test the docker install. Give me a few days to research and I'll see if I can replicate your issue.
