### ISSUE TITLE
Tests are very slow

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#134]
The tests under `experiments/MERA` are very slow and cause the travis build to take >10 minutes. The tests are also very slow when running on a laptop, which inhibits external contributors. We need to find a way to make these tests faster.

**Comment by Thenerdstation** [comment]
@mganahl These are both your tests. Can you please find a way to reduce the compute required to run them? It also seems like you are only doing end to end tests. It might be a good idea to just do unit tests (testing only 1 part at a time) as they should be much faster to run.

**Comment by mganahl** [comment]
I'll have a look. None of those tests is end to end though, I think.

**Comment by Thenerdstation** [comment]
Turns out it wasn't @mganahl fault at all. TF 1.14 sets `autograph=True`, which has nasty sides effects on our code. We'll be raising an issue with the autograph team to see what went wrong.
