### ISSUE TITLE
von Neumann entropy

### ISSUE THREAD

**Issue by chrisnakers** [google/TensorNetwork#145]
Consider a tensor network that defines a state on some dangling legs. I would like to be able to specify a subset of those legs and output the von Neumann entropy S = - tr ( rho log rho), where rho is the normalized density matrix of those legs.

**Comment by amilsted** [comment]
See #144.

**Comment by Thenerdstation** [comment]
I guess we can use a rule that "Anything not directly related to tensor networks won't be added, atleast not to `TensorNetwork`." In this case, it seems like this is too specific to quantum circuits to be justify it's addition.

However! That doesn't mean we can't add a `QuantumTensorNetwork` that has a lot of useful features like the above.

**Comment by chrisnakers** [comment]
This would be great!
