### ISSUE TITLE
ncon throws an obscure error for a valid contraction order

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#148]
Hey, I just noticed that the following code throws an obscure error:
```python 
d = 2
D1 = 4
D2= 5
a = tf.random_uniform(shape = [D1,D2,d,d])
b = tf.random_uniform(shape = [D1,d,D1])
c = tf.random_uniform(shape = [D2,d,D2])
f = tf.random_uniform(shape = [d,d,d,d])

tn.ncon([a, b, c, f], [[1,3,5,4], [1,2,-1], [3,4,-2], [5,-4,2,-3]])
```
The order above is not chosen smartly, but `ncon` should either throw an interpretable error, or do the contraction

**Comment by Thenerdstation** [comment]
What error does it throw?

**Comment by mganahl** [comment]
The error is thrown by `network_components.py`.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-ece68fe98643> in <module>
      7 f = tf.random_uniform(shape = [d,d,d,d])
      8 
----> 9 tn.ncon([a, b, c, f], [[1,3,5,4], [1,2,-1], [3,4,-2], [5,-4,2,-3]])

~/workspace/git_repos/TensorNetwork/tensornetwork/ncon_interface.py in ncon(tensors, network_structure, con_order, out_order)
     80   while con_edges:
     81     e = con_edges.pop(0)  # pop so that older nodes can be deallocated
---> 82     nodes = e.get_nodes()
     83 
     84     nodes_set = set(nodes)

~/workspace/git_repos/TensorNetwork/tensornetwork/network_components.py in get_nodes(self)
    428   def get_nodes(self) -> List[Optional[Node]]:
    429     """Get the nodes of the edge."""
--> 430     return [self.node1, self.node2]
    431 
    432   def update_axis(self, old_axis: int, old_node: Node, new_axis: int,

~/workspace/git_repos/TensorNetwork/tensornetwork/network_components.py in node1(self)
    459     val = self._node1()
    460     if val is None:
--> 461       raise ValueError("node1 for edge '{}' no longer exists.".format(self))
    462     return val
    463 

ValueError: node1 for edge '5' no longer exists.

**Comment by Thenerdstation** [comment]
That's strange... This seems less like a bad error message and more like a real bug. I'll investigate some more today.

**Comment by mganahl** [comment]
I think the problem is related to the bad contraction order. `ncon` calls `contract_between` (if I'm not mistaken). In the specified order above, contraction 2 and 5 could be done in one go, but I specified 4 and 3 to be done before. I think `ncon` should throw an error in this case telling the user that he chose a stupid contraction order (@amilsted did you implemented something along these lines?).

**Comment by Thenerdstation** [comment]
Ok I see what you mean now.

Well, I think it's important to maintain `contract_between` since it gives huge speed up. So we have 2 options of what we can do.

1. Check if the edge is still in the network before trying to contract it. If it's not in the network, just skip it.

2. Throw an error saying the contraction order is wrong.

I'm leaning more towards 1 since it'll be easier to write. I'm not sure there is any advantage in forcing the user to account for our use of `contract_between`

**Comment by mganahl** [comment]
I totally agree with maintaining `contract_between`. I also agree to have 1 in any case, since no matter how the user specifies the order, it should at least in principle be contracted (unless the order is ill defined). As for 2, it would be nice to at least throw a warning so the user is aware of his bad choice of contraction order. @amilsted mentioned at some point he had this implemented already because it is very easy to do it on the `ncon` level.  I think we can quickly fix the issue on the `ncon` level as well

**Comment by amilsted** [comment]
There is code to provide a reasonable error message for these kinds of ordering issues, but this looks like a case I missed. Possibly this is because the tensor network objects now raise exceptions where they didn't previously. Anyway, it's easy enough to handle this in the ncon code. Will submit a PR.

**Comment by Thenerdstation** [comment]
Yeah that's what I think happened too. We added additional error messages to deal with our usage of weakref. Seems to have broken some assumptions in ncon.
