### ISSUE TITLE
Rename tensornetwork.py?

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#15]
Currently, we have a module `tensornetwork.tensornetwork`, which I find unnecessarily ambiguous. Both `tensornetwork` and `tensornetwork.tensornetwork` provide `TensorNetwork`, but only one of them provides `ncon`, etc. 

Can we rename `tensornetwork.py` to `core.py` or somesuch?

**Comment by Thenerdstation** [comment]
I think what I'll likely do now is split up `tensornetwork.py` into `node.py`, `edge.py` and `network.py`.

**Comment by kshithijiyer** [comment]
@Thenerdstation are you working on this or is it up for grab?

**Comment by Thenerdstation** [comment]
We need to move some code from internal first before we break it up. That should be done soon so afterwards go for it.

**Comment by kshithijiyer** [comment]
Okay. Will wait for your go single on this one.

**Comment by Thenerdstation** [comment]
Once https://github.com/google/TensorNetwork/pull/22 is in you should be good to go.

**Comment by Thenerdstation** [comment]
Ok go for it.

Be sure that `Node`, `Edge` and `TensorNetwork` classes are publicly accessible from `import TensorNetwork`

**Comment by amilsted** [comment]
Hey, thanks for working on this @kshithijiyer. I noticed you still have a `tensornetwork.py`. Can we make it `network.py`?

**Comment by kshithijiyer** [comment]
Splitting the files is hitting a circular import error. Hence what I feel is that splitting the file into 3 files won't be possible but a split into 2 files would be possible.

**Comment by Thenerdstation** [comment]
Yeah I think you are correct. Basically, what happened is it would start to parse `node.py` and then hit `from tensornetwork import edge`, continue to parse `edge.py` until it hit `node.Node` type declaration and raise an undefined error. This only happens because we use pytype. 

Dang that sucks.

**Comment by Thenerdstation** [comment]
I think we can get around it by using strings for the typing instead of using the module directly.

**Comment by kshithijiyer** [comment]
I am not sure if that is a proper solution to this. This is what is happening when we split it into 3 files https://stackabuse.com/python-circular-imports/.
I feel a way out would be to have two files:
1. `support.py` -> Having classes `Node` and `Edge.`
2. `network.py` -> `TensorNetwork` class only

**Comment by Thenerdstation** [comment]
So I started working on this and what is frustrating is that the tests pass by pytype doesn't. I'll be sure to raise a bug on that internally.

**Comment by kshithijiyer** [comment]
@Thenerdstation I think we need to close this now right? As you have completed the and merged the new structure.
