### ISSUE TITLE
test_svd_consistency sometimes fails for JAX due to precision

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#151]
JAX (currently) forces everything to single precision by default. This can be changed at startup using
```python
from jax.config import config
config.update("jax_enable_x64", True)
```
Anyway, single precision seems to be causing `test_svd_consistency` to sometimes fail, since the tolerances are set for double precision.

**Comment by Thenerdstation** [comment]
I'd be ok with adding this line to the top of `tensornetwork_test`
