### ISSUE TITLE
Add a operator alias for connect

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#152]
I really liked using `a @ b` as an alias for `net.contract_between`, and I want something similar for `net.connect`. What symbol should we use?

**Comment by amilsted** [comment]
Yeah, was wondering about this too! Perhaps `*` or `&`? At some point, Martin suggested `-`, which is kind of neat, since it looks like and edge :). `~` is also quite edgy...

**Comment by Thenerdstation** [comment]
`~` or `-` would be a good. I personally prefer `~` if possible to differentiate it from tensor subtraction. (Is the tilde actually supported in python?)

We'll keep it as the same API since `new_edge = edge1 ~ edge2` would likely be very common. We already have checks for when you try to run connect with a non-dangling edge so `e1 ~ e2 ~e3` should already throw an error.

**Comment by Thenerdstation** [comment]
> This syntax does not make it possible to put multiple connections into one expression, unlike with contract_between.

You're not thinking out of the box enough!

```python
edges = [a[0] ~ b[0], a[1] ~ b[1], a[2] ~ b[2]]
```

**Comment by amilsted** [comment]
> You're not thinking out of the box enough!

You seem to be putting things *in* boxes! Feels like cheating :)
Btw, just realized that `~` is only unary (according to [this](https://docs.python.org/3/library/operator.html#mapping-operators-to-functions)), so that one's out :/

**Comment by Thenerdstation** [comment]
yeah I just say that too. Sad!

**Comment by amilsted** [comment]
How about `^`? It kind of looks like a line joining things up, and it's harder to mistake for tensor arithmetic.

**Comment by Thenerdstation** [comment]
`a ^ b` is another good option.

**Comment by Thenerdstation** [comment]
Gah you beat me to it. Ok, since we both came to the same conclusion let's go with it.

**Comment by amilsted** [comment]
It also just feels positive and optimistic. ^_^

**Comment by Thenerdstation** [comment]
^-^

**Comment by amilsted** [comment]
Also, the logical operation on indices is pretty much the inverse of XOR...
