### ISSUE TITLE
Splice notation for edges? 

### ISSUE THREAD

**Issue by sidek** [google/TensorNetwork#158]
We can access edges of a node by list notation, 
```
edge = node[0]
```
so it would be very nice (and useful, to me at least) if one could also access several edges of a node via splice notation 
```
edges = node[:4]
```
If this seems like a good idea, I'm happy to try implementing it.

**Comment by Thenerdstation** [comment]
You could do this right now with `node.edges[:4]`, but I agree having it built into the indexing would be move convenient. 

And go for it! We love getting PRs. :)
