### ISSUE TITLE
Relative imports under tensornetwork/

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#16]
Could we make it possible to use our code without installing it using setup.py? If we stick to relative imports within the `tensornetwork/` folder, such as `import decompositions` in place of `from tensornetwork import decompositions`, it would be possible to e.g. run the tests directly from source.

**Comment by Thenerdstation** [comment]
I don't see the issue?

Just call `import tensornetwork` just outside of the `tensornetwork/` directory. You'll be able to to access all of the public functions by doing that.

**Comment by amilsted** [comment]
The issue I stumbled across is that I can't do `python tensornetwork/tensornetwork_test.py` from just outside the `tensornetwork/` directory. The line `from tensornetwork import decompositions` in `tensornetwork.py` fails.

**Comment by Thenerdstation** [comment]
Just run it like `python3 -m tensornetwork.tensornetwork_test` from just outside of `tensornetwork/`. That works for me.

You can also just do `pytest` from the root directory. It runs very quickly for me (less than 2 seconds for all of the tests.).

**Comment by amilsted** [comment]
Ah, ok, that'll work!

**Comment by Thenerdstation** [comment]
You can also do `python3 -m pytest tensornetwork/tensornetwork_test.py`. This gives you the pretty pytest output.
