### ISSUE TITLE
Behaviour of "diag" method in backends

### ISSUE THREAD

**Issue by MichaelMarien** [google/TensorNetwork#160]
I was starting to look into #53 and as a start, to make sure the behaviour of the PyTorck backend would be 100% aligned with the other ones, I first added very basic unit tests of all the method in the backends. Stumbled upon the differing behaviour of tf.linalg.diag (always returns a tensor with provided diagonal values and zeros off-diagonal) and np.diag (depends on input) which are used in the respective backends. Although not 100% sure where the functions are currently used, I think we should straighten out the behaviour. However ,which is the preferred one?

**Comment by Thenerdstation** [comment]
Currently, `diag` is only used to make the singular values matrix, so the TF API is what we should follow.

**Comment by MichaelMarien** [comment]
@Thenerdstation perfect, thanks, will change it accordingly

**Comment by MichaelMarien** [comment]
Added a check on dimension in NumPy backend drag method in #161 and tests to ensure/clarify the correct behaviour
