### ISSUE TITLE
Graduation of experiments

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#162]
Some of the things in experiments like MPS, MERA, DMRG, and TTN would all be great to have  in the core tensornetwork library. We should begin work to graduate these to the core library.

This will likely mean they will have to go through a semi painful transition where we fight the linter and make API changes. However, I have a good feeling it will be worth it in the long run.

Which of these should we try to move first?

**Comment by mganahl** [comment]
I'd say MPS and DMRG will be the stuff that will get the most interest from the community, so I'd say those should be first.

**Comment by MichaelMarien** [comment]
I agree with @mganahl, not only is MPS the easiest to implement, it's still the most popular. Should of course come with some energy minimization algorithm.

**Comment by Thenerdstation** [comment]
Agreed. Let's add MPS first. @mganahl would you be willing to start the PRs for the migration? I'd recommend doing it in parts to help with the review process.

**Comment by mganahl** [comment]
Yes, I'm happy to do that! Once I'm on it, I'll restructure the MPS-library and also 
add some of the more recent optimization and real time evolution algorithms as well. 
Will take a bit of time though...

**Comment by Thenerdstation** [comment]
:+1:

**Comment by amilsted** [comment]
Let's think about this in conjunction with the "QuantumTensorNetwork" ideas in #155. Would be great to have a common API for operations on states and operators, no matter what the tensor network looks like!

**Comment by mganahl** [comment]
We can think about it,  but I'd prefer very much to keep it simple and add an MPS toolkit only. Generically,  it seems that "QuantumTensorNetwork" should subsume essentially every tensor network
geometry + generic quantum states. Unless we invest some real deep thinking, I'm worried this might become a burden to maintain.

**Comment by amilsted** [comment]
I agree that we need to be careful not to create a beast here. How about the following sort of very minimal interface? We give finite MPS and MPO objects a method that returns a `QuantumState` or `QuantumOperator`, say `as_quantum_state()`, `as_quantum_operator()`. All these do is generate a TensorNetwork for the full MPS or MPO, together with a list of dangling edges to provide a site ordering (two in the case of an MPO).

Then, in case someone wants to, say, plug and MPS into a Tree or a PEPS, they can convert each one to a `QuantumState` and then take the inner product.

In addition to this, we should try to keep interfaces for common functionality, like computing expectation values or entanglement entropies, as consistent as possible across the board.
