### ISSUE TITLE
Consistent usage of backend tensors

### ISSUE THREAD

**Issue by MichaelMarien** [google/TensorNetwork#164]
Currently, we are not 100% strict on the usage of the tensor types of each backend. For instance, in network._flatten_trace_edges we call backend.prod on a list, not a tensor object. 
https://github.com/google/TensorNetwork/blob/b6ac4a08b52b6c78d1169231d6c0ec06517dd25d/tensornetwork/network.py#L584
While some backends are more forgiven, this will for sure cause issues.

Should we be very strict in the backend implementation on the input types (must be a tensor of corresponding backend), or allow looser usage and deal with it in the backend (by always explicitly converting all input to tensors)?

**Comment by Thenerdstation** [comment]
Yeah, this is the messy part I was warning you about.

So here's the struggle. When using graph mode I tensorflow (when using v1 behavior or when using `tf.function` in v2), Tensors can have unknown shapes during graph construction but known shapes during computation. How does tensorflow deal with this? By making shapes a tf.Tensor! Thus the weird inconsistencies.

I think if you just ignore it and treat `prod` and `concat` as exclusively shape operators you should be ok.

**Comment by MichaelMarien** [comment]
Indeed, it is. Pytorch backend seems to pass all tests now. Can you confirm that prod/concat are only used with "shapes" as input, not the tensors itself?

**Comment by Thenerdstation** [comment]
Yes, that's definitely the case. We should probably rename these functions and improve the documentation to make that more apparent
