### ISSUE TITLE
Mixed Tensors and Christoffel Symbols

### ISSUE THREAD

**Issue by sgangoly** [google/TensorNetwork#170]
Hi Gurus,

Just a quick one and my apologies if this is covered in TN and I am missing it. I am brand new to TN (my disclaimer and vain attempt at face saving ) and have two queries really:

 1) Is there anyway I can represent a mixed Tensor via TN please? Something akin to a mix of a contravariant (upper index) and covariant (lower index)?

2) Is there any way to represent Christoffel symbols please?

I am looking at PEPS ( Projected Entangled Pair States) and also toying with the idea of trying to apply Quantum Wavefunctions in the Tolman Bondi matrix. Both PEPS  and application of Einstein's equations require mixed Tensors. Hence the query. 

Any kind guidance will be most appreciated please. 

A disclaimer: I work for Cisco Systems but this work has nothing to do with Cisco. This is related  entirely to my own private and personal interest.

Keep up the amazing work. Finally wanna be Physicists like myself can try out ideas thanks to Google X!

With gratitude and best regards

Santanu

**Comment by sleichen** [comment]
We don't make any distinction between upper and lower indices in the library. You are free to create nodes which represent mixed tensors or Chrstoffel symbols, but you'll have to keep track of which indices are which yourself.

**Comment by sgangoly** [comment]
Ahhh! Many thanks Stefan! That clears up some cobwebs in the empty space i refer to as my head.
Appreciate the guidance!
Santanu

**Comment by Thenerdstation** [comment]
To help with keeping track, you can always name your indices. 

```
a = net.add_node(tensor, axes_names=['alpha', 'beta'])
# We can now use the names instead of the axis numbers.
new_edge = a['alpha'] ^ a['beta']
```

**Comment by sgangoly** [comment]
> To help with keeping track, you can always name your indices.
> 
> ```python
> a = net.add_node(tensor, axes_names=['alpha', 'beta'])
> # We can now use the names instead of the axis numbers.
> new_edge = a['alpha'] ^ a['beta']
> ```

Fantastic Chase! Many thanks for that and your patience with my email(s) :-)

Appreciate the guidance very much!
santanu
