### ISSUE TITLE
Contractor output edge order.

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#179]
Right now, the edge output order for the contractors is inconsistent, and thus can lead to confusing results when trying to switch contractors. (The final node's shape is different for different contractors.)

We have 2 options here: 
1. Force users to give an order to the dangling legs via `contractors.optimal(net, edge_order=[...])` 
2. Give a default ordering for the dangling legs. We could do this by using the edge's signature, However, currently all dangling legs have a signature of -1. Otherwise, the order could be 1) the order nodes where created and then 2) the order of the axis number of the dangling edge.

Design 1. Is easier to code, but harder for the user, 2 is harder to code, but easier for the user. Ultimately, the user will likely want to set the final axis order anyway, do I'm leaning more towards 1.

Note: this isn't a problem for einsum since the equation must have an output order of indexes anyway.

**Comment by Thenerdstation** [comment]
@amilsted @mganahl I would love your opinions on this.

**Comment by mganahl** [comment]
I think choosing the order of creation is fine. How exactly do you get the order for 2)?
I agree that the user will usually keep track of the edges, but I'm actually leaning towards
forcing the user to pass the order. This would eliminate a possible source of bugs if the user forgets to reorder the edges.

**Comment by mganahl** [comment]
I can make a PR if no one else has already done so

**Comment by mganahl** [comment]
How should we deal with the case of disconnected parts in the final network? 
I would make the user provide a seperate list of `Edge`s for each remaining node in `nodes_set`. Any thoughts?

**Comment by Thenerdstation** [comment]
We already throw an error if the network is disconnected. Opt_einsum doesn't support multi output contractions. We can discuss later how to deal with disconnected, but right now we just won't support it.

And go for it! Love getting PRs. :)

**Comment by mganahl** [comment]
When testing `path_contractors_test.py` I get the following errors:
`TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`
It's originating from `np.testing.assert_all_close()` calls on `net.tensor`. 
I'm running tf 1.14, numpy 1.16.4.  Anyone having the same issue?

**Comment by mganahl** [comment]
btw, the `naive` contractor still supports disconnected networks.

**Comment by Thenerdstation** [comment]
You'll need to provide more context. What test fails? what code did you run to hit this?

**Comment by mganahl** [comment]
I'm simply running `pytest path_contractors_test.py`.
 Here's the output:
[error_log.txt](https://github.com/google/TensorNetwork/files/3488021/error_log.txt)

**Comment by Thenerdstation** [comment]
Oh, I think v2 behavior isn't enabled. Can you try adding `tf.enable_v2_behavior` to the top of the file?

**Comment by amilsted** [comment]
I think option 1 is preferable. Whatever default ordering chosen is almost certainly not what the user wants in a particular case, so better to require the user to specify it.

**Comment by MichaelMarien** [comment]
Related to this (not sure if I should make a separate issue), I find the following quite annoying. Suppose the following scenario, where I give clear names to my axis in a tensor and its conjugate.

```
from tensornetwork import TensorNetwork, Node
import numpy as np

tensor = np.random.randn(2,3,2)
ket_axis_order = ["ket_left_virtual", "ket_physical", "ket_right_virtual"]
bra_axis_order = ["bra_left_virtual", "bra_physical", "bra_right_virtual"]

net = TensorNetwork("numpy")
ket = net.add_node(tensor, axis_names=ket_axis_order, name="ket")
bra = net.add_node(np.conj(tensor), axis_names=bra_axis_order, name="bar")
edge = net.connect(edge1=ket["ket_physical"], edge2=bra["bra_physical"])
transfer_matrix = net.contract(edge, name='transfer_matrix')
```

The resulting node has its axis names reset to '__Edge_2', '__Edge_3',... However its dangling edges keep the original names 'ket_left_virtual',... The discrepancy is very confusing to me. I understand that, due to possible non-uniqueness, we cannot simply takeover the older axis names, but a better solution should be possible. 

Moreover, there seems to be no one line solution to now determine / fix the order of the axis of the resulting node (as far as I know).

**Comment by Thenerdstation** [comment]
@mganahl has brought this up too. And yes the naming collision is the reason for this weirdness. I'm open to suggestions for a fix to this.

**Comment by MichaelMarien** [comment]
@Thenerdstation, I checked #184 and this seems to fix it for the opt_einsum based contraction methods. I'll try to come up with a similar fix for this contraction API.

**Comment by MichaelMarien** [comment]
We should add the option to determine the output edge order also to `network.contract`, `network.contract_copy_node`,  `network.contract_between` and `network.contract_parallel`. This will have implications also to the contractors they use. So far so good, howler should we make this optional or required input? Second one makes most sense - as everybody here seems to agree - but it is a breaking change?

**Comment by Thenerdstation** [comment]
I think adding output edge order to every single contraction would be very cumbersome (and would break the use of `a @ b`). 

I'd be ok with adding it as an optional argument, but I'm not sure it's very needed.

**Comment by mganahl** [comment]
I would make it optional. The reason for enforcing it in the contractors is the inconsistency of the output between different backends, which was a real bug. If the above operations are all consistent between all backends I wouldn't worry too much (reordering the edges after the call is just one additional line).

**Comment by MichaelMarien** [comment]
@mganahl I guess I'm missing something! What's the one line of code to achieve this? My edges get renamed to "__Edge_x,..." and it is not straightforward to remember which one is which? Could you perhaps check my example above and clarify the best way to proceed?

**Comment by Thenerdstation** [comment]
Oh I think you mean the _axes names_ on the nodes.

Yes, that is an issue that we have been discussing trying to fix. The problem with that is what happens when you contract two nodes together that have the same axes name. Now you have two axes that have the exact same name and we don't know which one you want!

```python
a = net.add_node(np.eye(2), axes_names=["alpha", "beta"])
b = net.add_node(np.eye(2), axes_names=["alpha", "beta"])
a["alpha"] ^ b["beta"]
c = a @ b
c["beta"] # Which edge should be returned?????
```

Our current implementation right now just totally throws out the two old names and creates new default ones, which is where your "__Edge_x" comes into play.

Really there are 3 ways to handle this.
1. Completely throw out the names and replace them with defaults. (We initially picked this one since it was the easiest to do).
2. Force globally unique axes names. (This solution just seems.... bad. And it would be incredibly annoying when trying to merge networks together. Plus, I'm almost certain this work break existing examples in a really annoying to fix way.)
3. Merge the axes names together and throw an error if the axes name is ambiguous. 

I don't think anyone likes our current implementation, as both @mganahl and @MichaelMarien have complained about it, so I think it is time to start doing 3.

**Comment by MichaelMarien** [comment]
@Thenerdstation , yes indeed axis_names, as in my original description : ). I tend to confuse the two :). The order of the axis is the one that matters right? Do we really care about order of the edges?

**Comment by Thenerdstation** [comment]
Yes, order of the axis names is what matters. (Edge order is already handled).

**Comment by MichaelMarien** [comment]
Sorry to press on this, but I'm confused.

Irregardless of the issue / bug and the fixes, I'm just not sure why we care about edge order? In your original description you mention the final node's shape, but is this not determined by the axis order? Moreover, not all axis necessarily carry an edge, so if the current fix for the opt_einsum contractors only cares about edges, does it cover all issues?

**Comment by Thenerdstation** [comment]
Yes you are correct.

**Comment by MichaelMarien** [comment]
@Thenerdstation , thanks for the clarification. I'll focus on #203 , from my POV this one can be closed then?

**Comment by Thenerdstation** [comment]
SGTM.
