### ISSUE TITLE
split_node_qr

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#200]
Is that already there? If not, it would be nice to have for the MPS stuff (faster than svd)

**Comment by Thenerdstation** [comment]
We welcome PRs. 

I don't expect it to be very difficult to do. Would you be ok if I assign it to you?

**Comment by mganahl** [comment]
I'm almost done with it :)

**Comment by Thenerdstation** [comment]
Awesome! I look forward to it. ^-^
