### ISSUE TITLE
Weekly TensorNetwork Hangout Meeting

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#212]
Hey everyone! @stavros11 @sidek @amilsted @mganahl @MichaelMarien @viathor @Bonnevie,  we will be staring a TensorNetwork hangouts meeting every Friday at 3pm PT. 

Our first meeting will be around discussing the design of the MPS class. I'll post the hangouts link once we have a room booked.

**Comment by Thenerdstation** [comment]
@stavros11 @sidek @amilsted @mganahl @MichaelMarien @viathor @Bonnevie, We have decided to move the meeting to 2pm PT tomorrow.

Here is the hangouts link. Feel free to join in on the conversation!

https://meet.google.com/csz-zzin-cme

**Comment by MichaelMarien** [comment]
Won't be able to make it this time :(

**Comment by viathor** [comment]
I have a conflict today. See you next Friday!

**Comment by amilsted** [comment]
Sorry, couldn't make it this time.
