### ISSUE TITLE
Breakup tensornetwork_test?

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#215]
It's getting pretty large, >1,600 lines of code.

It doesn't matter that much, and I'm not sure how we would break it apart. `tensornetwork_test_2`?

**Comment by MichaelMarien** [comment]
Yes, it's annoying me also. I think there is some reasonable way to break them up, will take a look.
I'd prefer putting the tests into a single folder than, as more files will start to clutter the `tensornetwork`directory.

On a related note, should we not breakup network_componts? I think with the base node now (on which edges and node depend), we can keep base node on the original level, and put the edges and nodes in separate files in a network_components module. I feel if we want to do this, now is the time, as #205 might introduce more functionality and make it harder.

**Comment by Thenerdstation** [comment]
Yeah lets do that. Let's add a `tests/` at the root directory and move all of the tests that require `import tensornetwork` to there. We can split up `tensornetwork_test.py` however makes the most sense.
