### ISSUE TITLE
Deprecate add_copy_node

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#217]
With https://github.com/google/TensorNetwork/pull/216 now in, we no longer need `add_copy_node`. This will be deleted within the next few release cycles.

We will also move `contract_copy_node` to be on the `CopyNode` object.

**Comment by MichaelMarien** [comment]
Is this just a head's up, or do we want to start adding a deprecation warning? Can add a PR for that, suggest to just add deprecated library?
