### ISSUE TITLE
remove node.disable()  from contraction methods

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#219]
I  noticed that it's quite inconvenient that `contract_between` and `contract` disable the nodes. For MPS methods, I usually have a list of nodes that I  want to  contract one, e.g. 
nodes of the MPS and its complex  conjugate. I'd like to do things like this:

```python
net = TensorNetwork()
...
nodes  = list(...)  #list of nodes of net
conj_nodes = list(...) #list of conjugated nodes of net
result = []
for site in range(len(nodes)):
  out = net.contract_between(nodes[site], conj_nodes[site])
  result.append(out.reorder_edges([nodes[site][2], conj_nodes[site][2], ...]).tensor) 
```
This currently throws a ValueError

**Comment by Thenerdstation** [comment]
The easiest way to get around this is to store these edges _before_ you contract the nodes.

I thought about allowing an exception for dangling edges, but what if the dangling edge isn't part of the network anymore? (Say it got connected). Then what should we do? If really rather not return a non-existent edge.

All in all, accessing edges from a disabled node is very unstable, and generally bad practice. That's the reason we added disable in the first place.

**Comment by MichaelMarien** [comment]
Can we not achieve what you want by fixing #203 (looking into it)

**Comment by mganahl** [comment]
I know how to fix this, I just don't like to *explicitly* store the edges. Code already becomes quite long, and this seems like a place where one could shorten it without sacrificing too much stability. 
I'm actually not sure how unstable this would be. Do you know a practical example where this could cause problems?
There are certainly cases that could be confusing (as the one in #207 after splitting a node), but not sure how relevant they are in practice. 

Not sure how #203 would help with this. In any case, I'd like to avoid having to do another lookup.

**Comment by mganahl** [comment]
Another thing: passing a list of `Edge`s to `Node,reorder_edges()` that are not part of
`Node` should give a better error message (something like 'edges do not belong to Node')

**Comment by Thenerdstation** [comment]
Oh yeah that definitely should be fixed.

**Comment by Thenerdstation** [comment]
> Do you know a practical example where this could cause problems?

Here is one.

```python
a = net.add_node(...)
b = net.add_node(...)
c = net.add_node(...)
e = a[0] ^ b[0]
d = net.contract(e)
# Say a[1] is equal to d[0]
e2 = d[0] ^ c[0]
final = net.contract(e2)
# This edge doesn't exist in the network, but is still a dangling edge.
final.reorder_edges([a[1]])
```

**Comment by Thenerdstation** [comment]
> Another thing: passing a list of Edges to Node.reorder_edges() that are not part of
Node should give a better error message (something like 'edges do not belong to Node')

Can you make another issue for this? I don't want it to get lost in this discussion.

**Comment by mganahl** [comment]
yeah I'll submit one in a minute!

**Comment by mganahl** [comment]
OK, so in the  above example, if `a[1]` equals `d[0]` then 
`e2 = d[0] ^ c[0]` should already raise an exception, no?

**Comment by Thenerdstation** [comment]
What exception would it raise? This is valid until the last line when it would crash.

**Comment by mganahl** [comment]
Hehe,  I misunderstood `a[1] is equal do d[0]` as the return value of the access opartion being the same thus a[1] and d[0] being connected ... my  brain's not functioning properly

**Comment by mganahl** [comment]
OK so `a[1]` would still accessible, and `reorder_edges`  would raise an exception because `a[1]`  is not in  `final.edges`.

**Comment by Thenerdstation** [comment]
Exactly. And that gets hard to debug because we have no way to check if `a[1]` exists in the network because `a.network` is None
