### ISSUE TITLE
better error message for reorder_edges

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#220]
`Node.reorder_edges(edges)` should give a clearer error message when one or more of the passed eges in `edges`do not belong to `Node`. Currently this code 
```python 
net=tn.TensorNetwork()
a = net.add_node(np.random.rand(3,3))
b = net.add_node(np.random.rand(3,3))
c = net.add_node(np.random.rand(3,3))

c.reorder_edges([b[0], a[0]])
```
throws
```ValueError: Given edge order does not match expected edges. Found: [<tensornetwork.network_components.Edge object at 0x146f9a978>, <tensornetwork.network_components.Edge object at 0x14a02fb00>], Expected: [<tensornetwork.network_components.Edge object at 0x14a02fb00>, <tensornetwork.network_components.Edge object at 0x14a02fc88>]```

It should be changed to something like 
``` 
ValueError: some edges in `edges` do not belong to `Node`
```

**Comment by MichaelMarien** [comment]
@Thenerdstation : Housekeeping :)  this is fixed I believe?

**Comment by Thenerdstation** [comment]
Yes it is.

In the future, be sure to do "fixes #ISSUE_NUM" in the comment of the PR so that it'll automatically close it.
