### ISSUE TITLE
complex qr crashes on jax backend

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#221]
This crashes on my machine
```python

net = tn.TensorNetwork(backend='jax')
a = net.add_node(np.random.rand(3, 3) + 1j * np.random.rand(3, 3))
q, _ = net.split_node_qr(a, [a[0]], [a[1]])
```
with a `RuntimeError: Unimplemented: complex comparison 'LT'`

**Comment by mganahl** [comment]
This seems to be a problem with JAX. I'll post an issue there

**Comment by Thenerdstation** [comment]
Strange, why would the need a less than operation? Be sure to link this issue on that issue so we can keep track.

**Comment by mganahl** [comment]
How exactly do I do that?

**Comment by Thenerdstation** [comment]
Literally copy and paste the link of this issue into a comment on that issue. GitHub takes care of it. (Which is so cool! It's my favorite feature)

**Comment by mganahl** [comment]
Yeah just did that

**Comment by mganahl** [comment]
thanks!

**Comment by mganahl** [comment]
maybe we should wait with switching the backend until this is fixed. QR shows up quite a bit in applicatoins

**Comment by mganahl** [comment]
the other option is to implement QR via SVD for the jax backend for now

**Comment by Thenerdstation** [comment]
Seeing how we just implemented QR I'm not sure it's enough of a blocker to not so the switch

**Comment by mganahl** [comment]
this has been fixed on the JAX side!

**Comment by Thenerdstation** [comment]
Great
