### ISSUE TITLE
Add conj option to net.copy()

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#223]
For calculating norms and reduced density matrices, it would be nice to be able to do `net.copy(conj=True)` to conjugate all of the nodes.

We already have conj built into the backends https://github.com/google/TensorNetwork/blob/af16c219e3cc1a411c89314648eb059000c378b8/tensornetwork/backends/base_backend.py#L268 so we can simply use that.

**Comment by Patil2099** [comment]
@Thenerdstation Can I work on this issue? Can you also explain a little more about it?

**Comment by Thenerdstation** [comment]
Certainly!

So the `net.copy()` operation in `TensorNetwork` currently uses the exact same Tensors when copying the network. We want to add an operation to conjugate the Tensors if the user requests it. So you would need to add an optional `conj` argument to the copy function that defaults to False and basically use `self.backend.conj(node.tensor)` instead of just `node.tensor` when copying a node.

Be sure to add a test! (You'll need to also skip the Pytorch backend in that test since complex numbers are not supported in Pytorch).

**Comment by mganahl** [comment]
only skip it though for complex data types.

**Comment by Thenerdstation** [comment]
Yes good idea.

It might also be a good idea to have a `complex_data_test` once https://github.com/google/TensorNetwork/pull/222 is in that just doesn't have Pytorch as a backend.
