### ISSUE TITLE
Config imports torch and tensorflow

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#227]
`config.py` imports torch and tensorflow, causing errors when a user doesn't have both installed.

We can mitigate this by adding try/except statements around the imports and uses.

**Comment by Thenerdstation** [comment]
On that note, we need to add tests for when these packages are missing as expecting a user to have both torch and tensorflow installed isn't reasonable.

**Comment by Thenerdstation** [comment]
This is also the case for the `pytorch_backend`. It's my fault for letting these in...

**Comment by MichaelMarien** [comment]
@Thenerdstation, so True! With #183 coming in soon (?), will we keep tensorflow as required package?

**Comment by Thenerdstation** [comment]
@MichaelMarien Nope! Instead we will install `jax` and `jaxlib`, Or would you prefer nothing other than numpy be installed?

**Comment by Thenerdstation** [comment]
How do we test this in travis? It's very likely this mistake will pop up again.

**Comment by stavros11** [comment]
+1 on not requiring the user to have all backends installed and modify tests accordingly.

A small note for Windows users (if there are any!): As far as I know `jax` does not support Windows while `TensorNetwork` seems to work fine on Windows with a different backend. We can decide not to support Windows at all or, if not too messy, check if `jax` can be installed and if an error is raised switch the default backend to `numpy`. Or the cleanest would be to require only `numpy` but default to `jax` if it is already installed.

**Comment by mganahl** [comment]
Hey everyone, sorry that was actually my fault. I'll remove the dependencies!

**Comment by mganahl** [comment]
I would not recommend to not support windows. I think there are (still) many people using 
Windows (Guifre for example).

**Comment by mganahl** [comment]
I'd vote for having numpy as the only dependency. Many people are familiar with numpy and we could leverage this familiarity.

**Comment by MichaelMarien** [comment]
I'll add tests

**Comment by Thenerdstation** [comment]
Yeah, but guifre is going full time to Google within the next week or so, so eventually he'll have to switch to Linux.

**Comment by MichaelMarien** [comment]
I vote for keeping windows (and no I'm not using it!). 

@mganahl if I'm adding tests anyway it's a small one to fix the dependencies also in same PR, or did you already work on it?

**Comment by mganahl** [comment]
Hey @MichaelMarien no haven't done anything yet. Feel free to fix it! thanks!
