### ISSUE TITLE
make backend methods available from tensornetwork

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#230]
would be nice to allow things like this
```python 
from tensornetwork import config
config.default_backed='whatever'
a = net.add_node(tn.randn((2,3,4))
b = tn.conj(a.tensor)
c = tn.transpose(b, (2,1,0))
```
Edit: same for `tn.svd`, `tn.qr`

**Comment by mganahl** [comment]
Another point: should we allow `Node` objects as input to backend methods as well?
I'd say yes. Any thoughts?

**Comment by MichaelMarien** [comment]
> Another point: should we allow `Node` objects as input to backend methods as well?
> I'd say yes. Any thoughts?

I think yes, don't see a drawback. Moreover, in my mind it seems the easiest way to address some of your concerns in #208 , providing a node allows us to access more metadata of the tensor's special properties, like symmetries, ...

**Comment by Thenerdstation** [comment]
The problem with allowing backend methods through TN is which backend should be used at any given time? Just the default? That feels like it would get messy very quickly.

**Comment by amilsted** [comment]
For writing backend-agnostic applications it would indeed be handy to have an "official" way of using the backend code directly. See the Tree code, which invents its own backend at the moment.

Would it not be enough to make it easy to instantiate the desired backend?
```python
import tensornetwork as tn
be = tn.JaxBackend()
a = be.randn((2,3,4))
...
```

**Comment by MichaelMarien** [comment]
> Another point: should we allow `Node` objects as input to backend methods as well?
> I'd say yes. Any thoughts?

@mganahl perhaps make a different issue for this? Afraid it's getting lost here

**Comment by stavros11** [comment]
Is it correct to assume that this issue is about using backend methods in a scope that doesn't have a `TensorNetwork` object instantiated? Because if you have a `TensorNetwork` you could always do `net.backend` to access backend methods, right?

**Comment by mganahl** [comment]
Yes, and yes. Though I find it a bit strange to expose the user to a thing called `backend`...

**Comment by Thenerdstation** [comment]
It's not too strange. I would prefer that over assuming the backend through `tensornetwork.backend`

**Comment by mganahl** [comment]
instead of operating on `Tensor` we could have `tn.conj` and others take `Node` instead.
Then there can be no confusion about which backend to use (unless we decide to have a free
`Node`).

**Comment by Thenerdstation** [comment]
We've already decided to have free nodes. `add_node` accepts free nodes right now.

**Comment by mganahl** [comment]
Speaking of which, this seems broken
```python
net = tn.TensorNetwork(backend='numpy')
node = tn.Node(np.random.rand(2,2), name='a', axis_names=['1','2'])
net.add_node(node)
```
Is this the intended way of doing it?

**Comment by mganahl** [comment]
The problem is that a `Node` with `.network=None` is disabled.

**Comment by Thenerdstation** [comment]
No, `Node` is only accessible for typing reasons. I'm not sure it makes sense to allow non specialized nodes to be left dangling.

**Comment by mganahl** [comment]
So then I'm a bit confused. In which way do we support free nodes then (a free is for me a node with `.network=None`).

**Comment by Thenerdstation** [comment]
With `CopyNode`
