### ISSUE TITLE
support for symbolic tensor nodes

### ISSUE THREAD

**Issue by jacobmarks** [google/TensorNetwork#232]

**Comment by Thenerdstation** [comment]
Jake and I talked about this in person.

It would be nice to have symbolic tensors, especially things like unitary parameterization and randomness.

**Comment by mganahl** [comment]
Not sure how much sympy might support this, but it should be easy enough to implement
a sympy backend (at least for tensor contractions).  I experimented with this a while ago (combining numpy and sympy), and it gets  *very* slow though for large expressions.
