### ISSUE TITLE
Support for special tensors

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#238]
As discussed I'm starting this issue as a place where we can collect tensors that we'd like to support. So far we'd like to add 
1. Levi-Civita symbol
2. Clebsch Gordon coefficients

**Comment by jlbosse** [comment]
3. A "metric" or "complex conjugate" tensor. This is useful to calculate e.g. expectation values or absolute values of Tensor Networks

**Comment by Thenerdstation** [comment]
Do we still want to do this?

**Comment by mganahl** [comment]
Hmm, I don't think it's a priority. We can close it.
