### ISSUE TITLE
Add default to max_rejections in stochastic_contractor.stochastic()

### ISSUE THREAD

**Issue by gecrooks** [google/TensorNetwork#242]
The 'max_rejections' should have a reasonable default. If no default is reasonable, then some guidance on how to set this parameter should be given. max_rejections=10 seemed to work fine for me.

https://github.com/google/TensorNetwork/blob/6672f7e2be774b0510c5b460fcab1dc0835a3778/tensornetwork/contractors/stochastic_contractor.py#L101

**Comment by Thenerdstation** [comment]
I'm currently considering deleting `stochastic` and `naive` in favor of using exclusively the einsum contractors. (Einsum also supports randomized path finding).
