### ISSUE TITLE
jax backend is not supporting float64

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#251]
It seems that jax is converting float64 to float32:
```python 
net = tn.TensorNetwork(backend='jax')
node = net.add_node(np.random.rand(2,3)) #adds float64 tensor
print(net.dtype) #float32
```
This seems to be a problem with jax:

```python
a = jax.numpy.ones((2,2), dtype=np.float64)
print(a.dtype) #float32
```

**Comment by Thenerdstation** [comment]
There's a flag you need to set to enable float64. You can see an example at the top of tests/network.py

**Comment by mganahl** [comment]
There is still a problem though on our side. This code work fine:
```python 
net = tn.TensorNetwork(backend='numpy', dtype=np.float64)
node = net.add_node(np.random.rand(2,3))
```
The code is supposed to work for jax as well (`jax.numpy` accepts `np.dtypes`)
but when changing `backend` to `'jax'`, the same code breaks (unlesse the user explicitly enables float64). I think we should probably enable `float64 by default` (it's the default dtype of numpy too).

**Comment by mganahl** [comment]
I'll raise another issue for this
