### ISSUE TITLE
Support induce subgraph in the copy function

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#266]
Now that we are moving away from using `TensorNetwork` object, we should still allow copying a network via passing a collection of nodes to a `tensornetwork.copy(nodes)` function. 

Along with this, it would be nice if when we passed a subset of all the nodes that it would create an induced subgraph copy of the given nodes.

By this I mean that if `a` and `b` are connected by an edge and we do `tensornetwork.copy({a})`, then the returned set of nodes should only be a copy of `a` and the edge that used to connect `a` and `b` becomes a dangling edge.

**Comment by lingxz** [comment]
I can work on this.

**Comment by Thenerdstation** [comment]
Great!
