### ISSUE TITLE
Add `with NodeCollection(node_list):`

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#270]
Since we are now nuking the `TensorNetwork` object, we should have an easy way to collect nodes into a list/set automatically.

I purpose doing what Ash suggested before we decided to nuke `TensorNetwork` and use a `with` context manager.

It would look something like this

```python
node_set = set()
with NodeCollection(node_set):
  a = tn.Node(...)
  b = tn.Node(...)
assert nodes_set == {a, b}
```

If you passed a list instead, it would append to the list in the order the nodes were created.

I think this should be fairly easy to do, and it would alleviate most of my concerns around nuking `TensorNetwork`.

**Comment by lingxz** [comment]
Sounds good, I can work on this.

**Comment by Thenerdstation** [comment]
Great! Go for it!
