### ISSUE TITLE
Saving and loading for `Iterable[BaseNode]` objects

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#274]

**Comment by Thenerdstation** [comment]
I don't think much should change from the current implementation. @MichaelMarien do you have any thoughts?

**Comment by MichaelMarien** [comment]
No, it's a quick change. However, the custom persisting we have now will need small updates and fixes during the current API changes. I'm wondering if it's not better to substitute it for now with a more simple pickle-based persisting that does not need so much care taking?
