### ISSUE TITLE
Have contractors only return a `Node`

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#279]
Right now, all of our contractors return either a `BaseNode` or `TensorNetwork` depending on what was passed.

I think we should only return a `Node` object from now on. This fix will happen once `TensorNetwork` is fully nuked.

**Comment by bjliu** [comment]
I would like to work on this issue! This is my first time working on open-source though, so would need help.

**Comment by Thenerdstation** [comment]
Go for it! Email me at chaseriley@google.com if you need assistance.

**Comment by Thenerdstation** [comment]
#333 fixed this.
