### ISSUE TITLE
bug in reachable

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#287]
reachable has a bug:
```python 

backend='numpy'
nodes = [
  tn.Node(
      np.random.rand(2, 2, 2, 2),
      backend=backend,
      name='Node{}'.format(n),
      axis_names=[
          'node{}_1'.format(n), 'node_{}_2'.format(n),
          'node_{}_3'.format(n), 'node_{}_4'.format(n)
      ]) for n in range(4)
]
_ = [nodes[n][0] ^ nodes[n + 1][1] for n in range(3)]
subset = [nodes[0],nodes[1]]
print([b.name for b in tn.reachable(subset)]) #this should always print out all node names; however, sometimes it doesn't (you have to run it several times).
```
The problem is this:
```python 
def _reachable(nodes: Set[BaseNode]) -> Set[BaseNode]:
  if not nodes:
    raise ValueError("Reachable requires atleast 1 node.")
  node_que = collections.deque()
#==========bug===========
  seen_nodes = nodes #this should be an empty set
#============================
  node_que.append(list(nodes)[0])
  while node_que:
    node = node_que.popleft()
    for e in node.edges:
      for n in e.get_nodes():
        if n is not None and n not in seen_nodes:
          node_que.append(n)
          seen_nodes.add(n)
  return seen_nodes

```
*edit: it should be this
```python
def _reachable(nodes: Set[BaseNode]) -> Set[BaseNode]:
  if not nodes:
    raise ValueError("Reachable requires atleast 1 node.")
  node_que = collections.deque()
  initial_node= list(nodes)[0]
  seen_nodes = {initial_node}
  node_que.append(initial_node)
  while node_que:
    node = node_que.popleft()
    for e in node.edges:
      for n in e.get_nodes():
        if n is not None and n not in seen_nodes:
          node_que.append(n)
          seen_nodes.add(n)
  return seen_nodes

```

**Comment by Thenerdstation** [comment]
The problem with only having seen nodes be one of the given nodes is when the two given nodes are from disconnected graphs. One would assume it would give a set of all of the nodes from both graphs. The "fix" you have wouldn't allow for that.

Though having a flaky and non-deterministic behavior is also bad. I'm more curious as to why that happens.

**Comment by mganahl** [comment]
yes you're right, I actually realized that yesterday in bed :). The que initially has to hold all input nodes. The reason it breaks now is the following (I'll use numbers to distinguish different nodes):
assume you have  [`Node0, `Node1`, `Node2`] where `Node1` connects to `Node2` and `Node2` to `Node3`. if you do
```python 
reachable([Node0, Node1`])
``` 
then the original code in `_reachable` has `nodes={Node0, Node1}` (because `reachable` converts the input to a set) and `seen_nodes = {Node0, Node1}`. Sometimes, `list(nodes)[0]` returns `Node0` into the deque. The algorithm then looks at all nodes connected to `Node0` and puts them into `seen_nodes` and the deque, if they are not yet there. However, `Node1` __is__ already in `seen_nodes` and is thus never added to the deque, even though it should be added because we haven't yet checked all of its connections

**Comment by Thenerdstation** [comment]
Yes that fix looks good. Be sure to add a test!
