### ISSUE TITLE
Implement tn.reduced_density operation

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#291]
I want an easy want to calculate reduced density operations. The API would look like.

```python
nodes_dict, edges_dict = tn.reduced_density(traced_out_edges)
```

Underneath, we would copy/conjugate all of the nodes in reachable by the `traced_out_edges` and return a dictionary of the old nodes/edges to the copied nodes/edges. We would then connect all of the edges in `traced_out_edges` to their copies.

**Comment by ShreeVishwa** [comment]
Hi, I would like to work on this issue. As this is my first time contributing to the open source project, I would like to have a little guidance on what has to be done.
