### ISSUE TITLE
algebraic operations for BaseNode

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#292]
It would be convenient to have addition, subtraction, multiplication by scalar and division by scalar for `BaseNode`s:

```python 
a, b =tn.Node(np.random.rand(3,3)), tn.Node(np.random.rand(3,3))
c=a + b
d = a*10
e = a/5
```

**Comment by miriyalavignesh** [comment]
Hey I want to work on this issue, I am guessing this should be little bit straight forward. Since this is mostly implementing operator overloading for TensorNetwork, please let me know if there are more caveats which are not obvious.

**Comment by Thenerdstation** [comment]
Great! Go for it.

Yes you'll need to overload the `Node` classes `__add__`, `__mul__` etc methods and then modifying the underlying tensors based on their backends. I would recommend adding them to the `BaseNode` class and throwing `NotImplemented` errors for node types that don't support these types of ops. (For example, `CopyNode` shouldn't support these operations.)

You'll then need to add the `add`, `multiply`, etc operations to `BaseBackend` and then add them to the concrete backend classes.

**Comment by IllgamhoDuck** [comment]
@Thenerdstation How is this issue going on? I checked the PR of this issue but seems not merged yet. Seems __add__, __sub__ is made and __mul__, __div__ yet can I work on this issue?
