### ISSUE TITLE
Add "Free Node" API support for the graph_viz visulalization.

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#296]
Right now, `tn.to_graphviz` only supports the `TensorNetwork` object, which has been deprecated. It should support passing in an iterable collection of nodes.

**Comment by longdead-ai** [comment]
I would like to fix this.

**Comment by Thenerdstation** [comment]
Great! Go for it.

Should be pretty straight forward. Ping me on here if you need help

**Comment by longdead-ai** [comment]
Has anyone run graphviz_test.py? when I ran it gave an error which I think it should.
    AttributeError: module 'graphviz' has no attribute 'Graph'
Should I change the file name or there is something that I don't know.

**Comment by Thenerdstation** [comment]
Test runs fine for me. Are you running python3? Also, what version of graphviz are you using? I just tested it with 0.11.1 and it was fine.

**Comment by Thenerdstation** [comment]
I would also support changing the filename if that fixes the issue on your end.

**Comment by Thenerdstation** [comment]
#333 fixed this.
