### ISSUE TITLE
GPU does not support SVD for complex values

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#31]
Apparently this is known, but has not been fixed: See [this TF issue](https://github.com/tensorflow/tensorflow/issues/12917).

NVidia's cuSOLVER library supports complex valued SVD, so this is just TF not using it: https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvd

**Comment by amilsted** [comment]
Note: The TF issue referenced is currently closed, but I recall @Thenerdstation raised this internally.

**Comment by Thenerdstation** [comment]
JAX should support this now.
https://github.com/google/jax/issues/723

**Comment by Thenerdstation** [comment]
Closing as this is out of our scope.
