### ISSUE TITLE
Nuke `TensorNetwork`

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#312]
We should nuke `TensorNetwork` soon, as nearly all features support free nodes at this point.

**Comment by Thenerdstation** [comment]
This will require more than just deleting the file.

* Remove the `network` component in `Node`s
* Remove the use of `TensorNetwork` for typing everywhere.
* Remove support of `TensorNetwork` in the contractors.

**Comment by MichaelMarien** [comment]
I can look at this, or do you prefer to do this one yourself?

**Comment by MichaelMarien** [comment]
Do we want to keep (a network free version of) bucket_contractor?

**Comment by Thenerdstation** [comment]
Yes if possible.

**Comment by MichaelMarien** [comment]
Ok, I'll try to port it. I'm double checking on any functionality we loose when nuking TensorNetwork. I guess the following methods of TensorNetwork are no longer relevant / don't make sense in a Free Node world:

* add_subnetwork
* merge_networks

I'm less sure about
* get_final_node
* switch_backend

Especially the latter seems something we still want on Node (or Node collection) level?

**Comment by Thenerdstation** [comment]
Yes `add_subnetwork` and `merge_subnetworks` are no longer needed.

`get_final_node` is also no longer needed, as the contractors return only a `Node` now.

`switch_backend` could still be added. Just have it accept an `Iterable[BaseNode]`.

**Comment by MichaelMarien** [comment]
We were throwing errors when a TensorNetwork was created in a backend that is not available. Do we want this now when a node is created?

**Comment by Thenerdstation** [comment]
Yes.

**Comment by MichaelMarien** [comment]
Ok, almost through it, just need to fix the bucket contractor thingy.

**Comment by Thenerdstation** [comment]
:+1:
