### ISSUE TITLE
If a single-node contraction has an output_edge_order, its edges should be reordered

### ISSUE THREAD

**Issue by verult** [google/TensorNetwork#317]
Currently if a contractor is passed in a single node, nothing is done.

https://github.com/google/TensorNetwork/blob/a1bcaed7fc1ab9204ca1b48053873562cadc3c9e/tensornetwork/contractors/opt_einsum_paths/path_contractors.py#L74-L76

But if `output_edge_order` is passed in, I would expect the edges to be reordered accordingly. If this is the desired behavior I'm happy to help with adding the fix!

**Comment by mganahl** [comment]
Hey @verult, thanks for noticing! This is a bug and should be fixed. PR's are very welcome!

**Comment by Thenerdstation** [comment]
Yes def a bug. Also seems like a really nice first PR for a 20%er ;)

**Comment by Thenerdstation** [comment]
Sorry for the scoop. Needed it fixed for something internal
