### ISSUE TITLE
tf.transpose can be very slow to execute on CPU

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#32]
Transpose gets very slow if the tensor has rank > 8.
TF issue https://github.com/tensorflow/tensorflow/issues/27383

**Comment by amilsted** [comment]
May I ask why you decided to close this? Is it no longer the case?

**Comment by Thenerdstation** [comment]
It's not something we can fix on our end.

**Comment by amilsted** [comment]
True, but I thought we were using this (and e.g. #31, #34) to keep track of backend issues that are relevant to us. If you don't want to do that, that's okay with me, but I personally find it useful.
