### ISSUE TITLE
documentation is not displaying properly

### ISSUE THREAD

**Issue by tanlin2013** [google/TensorNetwork#322]
Dear TensorNetwork team,

there are few sections in documentation that are not displaying properly. Please consider to rebuild sphinx or investigate the issue... thanks!

for instance:
https://tensornetwork.readthedocs.io/en/latest/tensornetwork.html

best,
tan

**Comment by Thenerdstation** [comment]
Yes I just saw that too. Thanks for pointing that out!

We need to include the Sphinx build in our Travis ci

**Comment by Thenerdstation** [comment]
huh, strange, it builds for me fine. Something is broken on the readthedocs end...

**Comment by Thenerdstation** [comment]
Even stranger, the build is complaining about not finding `scipy`, but we don't even use scipy...

```
WARNING: autodoc: failed to import function 'contractors.greedy' from module 'tensornetwork'; the following exception was raised:
No module named 'scipy'
```
https://readthedocs.org/api/v2/build/9805425.txt

**Comment by Thenerdstation** [comment]
Woops turns out we do.

https://github.com/google/TensorNetwork/blob/068be47d273c0868d768f697d998912acb15b716/tensornetwork/backends/numpy/numpy_backend.py#L19

**Comment by Thenerdstation** [comment]
That weirdly seemed to fix it.

Closing for now. I'll be sure to add build tests for the CI as well so that this doesn't happen again.

**Comment by tanlin2013** [comment]
thank you Roberts!

**Comment by Thenerdstation** [comment]
You are welcome!
