### ISSUE TITLE
Improve code coverage for tests and add coverage to CI

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#325]
Our code coverage is pretty good right now at 95%, but we should strive for 100%.

Most of our uncovered lines are for certain `raise ValueError` cases, which should be straight forward to fix. 

Another large majority of the uncovered lines are in the `TensorNetwork` class, so we'll wait until #312 is finished before we add coverage to the CI.

**Comment by darkMatter00** [comment]
I would like to do it.

**Comment by MichaelMarien** [comment]
> Another large majority of the uncovered lines are in the `TensorNetwork` class, so we'll wait until #312 is finished before we add coverage to the CI.

I'll prob be able to fix this during the weekend

**Comment by MichaelMarien** [comment]
#312 is closed, @darkMatter00 go for it!

**Comment by Thenerdstation** [comment]
Yes go for it.

**Comment by MichaelMarien** [comment]
I'm working on network_components now as it is only at 65%. Can easily add the coverage as I have it locally already. @Thenerdstation do you want a threshold for coverage breaking the build?

**Comment by Thenerdstation** [comment]
Really? It's that low? That is really surprising. Especially since last time I checked we were at nearly 95%

And yes, we should have a delta coverage of 100% while we continue to improve existing coverage

**Comment by MichaelMarien** [comment]
Yeah, I was just running the dedicated test in network_components_free_test for speed. If run all tests, it's 93%

**Comment by MichaelMarien** [comment]
@Thenerdstation how do you feel about testing protected methods? I know probably best practice in OO programming is to only test public methods. However, we have quite some protected helper functions in network_components that contain rather complicated logic. In this case I usually prefer to test them directly also as I think it increases coverage that way. Wdyt?

**Comment by Thenerdstation** [comment]
I'm ok with testing protected methods.
