### ISSUE TITLE
NodeCollection behavior after contraction

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#328]
So for this code

```python
nodes = []
with tn.NodeCollection(nodes):
  a = tn.Node(...)
  b = tn.Node(...)
  a[0] ^ b[0]
  c = a @ b
```

The `nodes` list will be equal to `[a, b, c]`, even though `a` and `b` no longer "in the network". Is this what we want to happen? If not, then what should we do in this situtation? 

Here are my proposals:

1. Nothing, leave this behavior as is.
2. Remove any contracted nodes from the collection. This could cause unneeded slow downs when the collection is a list.
3. Raise an error if a contraction happens while under a `NodeCollection` context.

Inputs are welcome!

**Comment by mganahl** [comment]
Hmm, not sure. I think can leave it as it is for niow.
