### ISSUE TITLE
Copy a TensorNetwork without copying the Tensors

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#33]
I would like a convenient way to copy a `TensorNetwork` without copying the Tensors associated with nodes. I don't think I can just use `deepcopy` for that, since it would copy the Tensors too?

This could be useful for algorithms involving finite tensor networks. We could set a network once for e.g. a matrix product state, then create copies before contracting subnetworks for various computations (e.g. compute the norm or energy).

**Comment by Thenerdstation** [comment]
Could you provide a code sample of your ideal workflow?

**Comment by Thenerdstation** [comment]
If your network creation is wrapped in a function, you should just be able to regenerate a TN with whatever tensors you want.

**Comment by amilsted** [comment]
Yeah, that's true. And the (negligible) cost of doing so would be about the same as the copy, I expect.

**Comment by amilsted** [comment]
Never mind :)

**Comment by Thenerdstation** [comment]
I do want to build a `TensorNetworkShell` class that doesn't have tensors. That would be useful for contraction algorithms.
