### ISSUE TITLE
Add `with tn.DefaultBackend("backend_name"):` support

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#339]
Currently, the only way to set a backend for a `Node` is either manually set it for each node or globally with `set_defualt_backend`. It would be nice to have a context manager instead, as it would be cleaner.

**Comment by mchav** [comment]
Will work on this.

**Comment by Thenerdstation** [comment]
Great! Go for it

**Comment by mchav** [comment]
Discussed this offline and I'm not sure a context manager would be the way to do this. Especially since by design they are typically meant to manage resources. In this case we want to capture common state which is what a context manager does but only as a bi-product of handling a resource.

I think we should instead have a context object that holds any "global" state specific to node creation.

**Comment by Thenerdstation** [comment]
In situations like the one above where classes that use/extend the library, having an easy way to make sure all nodes created have the same backend (vs pass `self.backend.name` to each created `Node`) would be preferable.

**Comment by mchav** [comment]
Agreed. But I think:

```python
    # Optional context object.
    context = tn.NodeContext(self.backend.name)
    a = context.Node([1, 2])
    b = context.Node([3, 4])
    ...
```

Is more idiomatic than:

```python
    a = None
    b = None
    with tn.DefaultBackend("backend_name"):
        a = tn.Node([1, 2])
        b = tn.Node([1, 2])
    ...
```

For a couple of reasons.

* Context managers are usually used to [manage resources](https://book.pythontips.com/en/latest/context_managers.html) and this situation has no resource that needs to be managed or is in contention.
* The design seems brittle. For example suppose a new parameter, similar to backend, was added to the node class. You'd need to nest contexts to capture this new information.

```python
    a = None
    b = None
    with tn.DefaultBackend("backend_name"):
        with tn.OtherGlobal("param"):
            a = tn.Node([1, 2])
            b = tn.Node([1, 2])
    ...
```

So it seems this situation requires an auxillary object to store the information. I think the TensorNetwork object provided that but was somewhat misnamed and didn't have to be compulsory.

**Comment by Thenerdstation** [comment]
#434
