### ISSUE TITLE
Add `tn.copy_node`

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#344]
The `tn.copy` operation is a little API heavy for just copying a single node. For example, the shortest code you can write to copy a single node looks like:

```python
a = tn.Node(...)
a_copy = tn.copy(a)[0][a]
``` 

The `[0][a]` can be kinda messy, so it would be nice to have just a `tn.copy_node` operation to make this more obvious.

**Comment by MichaelMarien** [comment]
Perhaps `tn.copy_node` is not the best naming convention, given we have a `CopyNode`class?

**Comment by Thenerdstation** [comment]
oh shoot good point.

**Comment by Thenerdstation** [comment]
I am open to suggestions. I agree we shouldn't use this name.

**Comment by ayush2804** [comment]
Can I work on this issue?

**Comment by Thenerdstation** [comment]
Go for it.

**Comment by ayush2804** [comment]
ok@Thenerdstation

**Comment by amilsted** [comment]
Since we have more than one type of `BaseNode` right now, should we maybe have `BaseNode.copy()` implementations for the subclasses? Then `tn.copy()` and `tn.copy_node()` can just call `node.copy()`, irrespective of the subclass.

**Comment by MichaelMarien** [comment]
Yes!

**Comment by Thenerdstation** [comment]
good idea!

**Comment by jacksonwb** [comment]
Were you thinking BaseNode.copy() is an abstract method and then implement on Node and CopyNode classes? And then a call to this would always result in a new node with all dangling edges correct?

**Comment by amilsted** [comment]
> Were you thinking BaseNode.copy() is an abstract method and then implement on Node and CopyNode classes? And then a call to this would always result in a new node with all dangling edges correct?

Yes to all of that!

**Comment by Thenerdstation** [comment]
+1

**Comment by Thenerdstation** [comment]
Closing as we now have a `node.copy()` method.
