### ISSUE TITLE
Backends have fixed dtypes

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#349]
Why is it that, currently, backends have a dtype field? Judging by how it is used in `convert_to_tensor()`, it seems to be forced on all tensors if it is set (not `None`), with exceptions raised if, e.g. I try to create a tensor from real valued inputs (`float64`) when the dtype is complex (`complex128`).

This surprised me - I could imagine it being the "default" dtype for new tensors, but I didn't expect it to be enforced like this. I expect there is a good reason?

It seems that the backend object created for a new `Node` has the dtype field set, so this is the default behavior, I guess.

**Comment by Thenerdstation** [comment]
This was left over from the `TensorNetwork` to ensure that all of the Tensors had the same dtype in the network, as mixing dtypes caused issues in some cases. I'm willing to change it though.

**Comment by mganahl** [comment]
Yes, I think `Node.dtype` should just return `tensor.dtype`, and we should remove `dtype` completely from the backends. 

The backend in `Node` is initialized with `dtype` field is set to `None`. Later on, the backend object deduces its `dtype` from `tensor.dtype` at the end of initialization of `Node`. The whole process is a bit convoluted, so I'd welcome a simplification.

**Comment by Thenerdstation** [comment]
Yeah, I think it'll be easier to remove `dtype` from the backend entirely and just check dtypes when nodes are connected

**Comment by Thenerdstation** [comment]
@mganahl wanna take lead on this?

**Comment by mganahl** [comment]
cando!
