### ISSUE TITLE
Add better __repr__ for Node class

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#353]
We don't have a good repr for the `Node` class yet.

**Comment by beinganonymous** [comment]
@Thenerdstation How do you want the representation to be ?

**Comment by Thenerdstation** [comment]
Good question! I think we should discuss it on here.

Ideally we should print these things: the node's name, it's underlying tensor value, its edges and how it's connected to other Nodes.

I'm open to hearing ideas about how it should be formatted

**Comment by drigio** [comment]
Hey @beinganonymous @Thenerdstation mind if I look into this? :)

**Comment by beinganonymous** [comment]
Sure go ahead I was going to ask to reassign this to someone else anyways. @drigio

**Comment by Thenerdstation** [comment]
Go for it!

**Comment by drigio** [comment]
Thanks! 
```
Node( tensor : array([[[1.]]]), name : 'Node A', edges : [Edge( 'Node A'->'Node B' ), Edge( 'Node A'->'Node C' ), Edge( Dangling Edge )] )
Node( tensor : array([[[1.]]]), name : 'Node B', edges : [Edge( 'Node A'->'Node B' ), Edge( Dangling Edge ), Edge( Dangling Edge )] )
Node( tensor : array([[[1.]]]), name : 'Node C', edges : [Edge( 'Node A'->'Node C' ), Edge( Dangling Edge ), Edge( Dangling Edge )] )
Node( tensor : array([[1.]]), name : '__unnamed_node__', edges : [Edge( Dangling Edge ), Edge( Dangling Edge )] )
```
@Thenerdstation How about such a format? What are your thoughts?

**Comment by Thenerdstation** [comment]
Looks pretty nice!

Here is what I would change:

1. For the edges, be sure to include the axis numbers/names
2. Perhaps make this multiple lines?

Thanks for taking time in looking into this!

**Comment by drigio** [comment]
I don't have an idea about how to display the axis numbers. By far what I've achieved is : 
```
Node
(
name : 'Node A',
tensor : 
array([[1.],
       [1.]]),
edges : [
Edge('Node A'->'Node B' ) Axis 1 : 0, Axis 2 : 0 
, 
Edge('Node A'->'Node B' ) Axis 1 : 1, Axis 2 : 1 
] 
)

Node
(
name : 'Node B',
tensor : 
array([[1.],
       [1.]]),
edges : [
Edge('Node A'->'Node B' ) Axis 1 : 0, Axis 2 : 0 
, 
Edge('Node A'->'Node B' ) Axis 1 : 1, Axis 2 : 1 
] 
)

Node
(
name : '__unnamed_node__',
tensor : 
array([[1.]]),
edges : [
Edge( Dangling Edge )
, 
Edge( Dangling Edge )
] 
)
```
Also would be good if you'd point me how to fetch the axis names from the edges!
Apologies for the late responses.

**Comment by Thenerdstation** [comment]
I think this should be good for now. Thanks for building this! I look forward to the PR.

**Comment by Thenerdstation** [comment]
Maybe my only change would be to change
```
Edge('Node A'->'Node B' ) Axis 1 : 0, Axis 2 : 0 
```

to 
```
Edge('Node A'[0] ^ 'Node B'[0] ) 
```
since `nodea[0] ^ nodeb[0]` is a pretty common way to connect nodes together in this library.
