### ISSUE TITLE
rename backend shape methods

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#355]
Some shape methods like `prod`, `concat`, and `shape` are exclusively used for shape calculations, but the naming is confusing. We should change these.

Suggested changes:

`prod` -> `shape_prod`
`concat` -> `shape_concat`
`shape` -> `shape_tensor` (as to differentiate it from `shape_tuple`)

**Comment by Patil2099** [comment]
@Thenerdstation Can I work on this issue?

**Comment by Thenerdstation** [comment]
Sure, go for it.

But be aware, it's a big change and all of the tests have to pass before we pull it in.

**Comment by kosehy** [comment]
@Thenerdstation How's the issue going on? I checked the PR about this issue and it is still not merged.
Can I continue this work? I have progress on this issue, and I passed Travis ci.
