### ISSUE TITLE
Enable contractor contraction on disconnected graphs

### ISSUE THREAD

**Issue by fangzhangmnm** [google/TensorNetwork#372]
When we are using tensor network to represent a tensor in the quantum physics, there is no rule that the network must be connected. for example, we can represent an exterior product from two non-connected nodes.

**Comment by Thenerdstation** [comment]
Thanks for your issue!

How would you want the final result returned? We can either

1. Outer product the final set of tensors together or 
2. Return the nodes in a set.

Option 1 would be the easiest to implement on our side. Option 2 might be difficult for the user to use, since the nodes are in a set and can be hard to distinguish.

**Comment by Thenerdstation** [comment]
Well actually now that I think about it both would be amount equal in difficult to implement. I still prefer 1 as that is what I assume you actually want.

**Comment by fangzhangmnm** [comment]
> Well actually now that I think about it both would be amount equal in difficult to implement. I still prefer 1 as that is what I assume you actually want.

1 is what I wanted in my current project. 2 might be helpful when there is a memory bottleneck.  However, if optimization is needed, one should explicitly split the graph, so i feel 2 is not very useful.

I just found there is a "tensornetwork.outer_product_final_nodes" method which might turn 2 to 1. 
Thank you very much

**Comment by Thenerdstation** [comment]
We should be able to do this automatically for you though. I can do this pretty easily, as all we have to do is contract each disconnected subnetwork and then just outerproduct the results.

I can add this in the next release.

**Comment by Thenerdstation** [comment]
So I wrote something I thought would fix it but I'm hitting a crash in the opt_einsum library. It's likely my fault, so I'll follow up on this next week.

**Comment by amilsted** [comment]
I would also like to have this, and prefer option 1.

We should also probably have a function that identifies and returns all disconnected subnetworks from a given set of nodes.

**Comment by Thenerdstation** [comment]
I can add both

**Comment by Thenerdstation** [comment]
Turns out it was way easier than I thought it would be.

**Comment by Thenerdstation** [comment]
All contractors should support disconnected graphs now. This will be included in the next release cycle.
