### ISSUE TITLE
ncon should take a BaseBackend object

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#387]
Since we are now supporting passing `BaseBackend` to `Node` constructors, we should also
allow it in `ncon`

**Comment by Thenerdstation** [comment]
Yes. Should be easy to fix right? I think we just need to update the typing

**Comment by mganahl** [comment]
that's right, I think it should be woring already

**Comment by mganahl** [comment]
has anyone taken the lead on this?

**Comment by Thenerdstation** [comment]
No, but this should be pretty easy for a contributor to do.

**Comment by jin14** [comment]
Hi I would like to work on this issue. If I understand this issue correctly, the function parameters for ncon and ncon_network should be updated to accept both Text and BaseBackend object?
