### ISSUE TITLE
matrix product operators

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#390]
We definitely need an MPO class for MPS simulations like DMRG, ...
I would suggest a structure similar to the MPS case, i.e.
* BaseMPO
* FiniteMPO(BaseMPO)
* InfiniteMPO(BaseMPO)

We also need convenience functions to build e.g. MPOs for
local Hamiltonians. I would suggest something along the line
```python 

mpo = tn.FiniteMPO(backend='numpy')

Sz = mpo.backend.Sz(dimension=2) #other operators need to be supported as well
site1, site2 = 2, 3
coupling=1.0
mpo.add_two_body(Sz,Sz, site1, site2, coupling)
```
any input welcome!

**Comment by amilsted** [comment]
Yes, this would be great! Do you already have external code to build MPOs like this?

Also desirable: Automatic decomposition of multi-site operators into MPO components (via SVD).

**Comment by mganahl** [comment]
I don't, but I'm thinking about how to build this. It's pretty straightforward if you just do it numerically, i.e. sum up individual MPOs and then run a compression algorithm on it (see https://arxiv.org/abs/1611.02498 for a recent review). Since they are simply finite state automata I think some results from computer science could be used to build the MPO algebraically, which could have certain advantages.

**Comment by Thenerdstation** [comment]
Closing as these exist now.

**Comment by amilsted** [comment]
They do?
