### ISSUE TITLE
extend pytorch, tensorflow and jax backends

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#397]
currently our default  numpy backend is the most developed backend. For example,
the `InfiniteMPS`  class only really works with this backend. We need to implement
the missing functions into the other backends as well. The numpy backend can serve as the 
"template" API for these methods.

**Comment by MichaelMarien** [comment]
I'll take up pytorch. Does the `BaseBackend` still contain the full API?

**Comment by mganahl** [comment]
Yes it does. thanks!

**Comment by MichaelMarien** [comment]
@mganahl, am I missing something or are the only missing functions `eigsh_lanczos`and `eigs`?

**Comment by Thenerdstation** [comment]
Closing as the `eigs` are supported in all but TF.
