### ISSUE TITLE
random_uniform initialization for backends

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#398]

**Comment by FollowKenny** [comment]
Hello,

I’d like to help on this one. If I understand correctly (considering the amount of information provided :) ), the goal is to add a method rand_uniform to each backend classes ?

**Comment by mganahl** [comment]
that's right, all backend (`BaseBackend, NumPyBackend, TensorFlowBackend, PyTorchBackend, JaxBackend, ShellBackend`) should implement it (or raise a `NotImplementedError`)!
The implementation should largely parallel `randn`. Thanks for your help!!
