### ISSUE TITLE
Add tests for the examples and experiments

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#40]
We should have some simple tests for this stuff (but not huge computations) that are automatically run by pytest. That way things won't get incompatible (as they already have at least once). Currently only 3sat has tests (AFAIK).

**Comment by Thenerdstation** [comment]
Yes please add tests. It's strictly enforced for `tensornetwork/`.

**Comment by amilsted** [comment]
There are still no tests for some things (in particular, the stuff I added!). Do you want specific issues for those?

**Comment by Thenerdstation** [comment]
I can reopen this and assign it to you

**Comment by Thenerdstation** [comment]
What else is missing tests currently?

**Comment by amilsted** [comment]
Tree tensor network stuff is missing tests (and docstrings).

**Comment by Thenerdstation** [comment]
Are we good to close this now?

**Comment by amilsted** [comment]
Not yet. Hope to produce a PR for the tree stuff later today.
