### ISSUE TITLE
Einsum support?

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#400]
Should we extend our API to support einsum equations? It could potentially make connecting nodes much less verbose. However, I question whether anyone would want to use `tn.einsum` over say `np.einsum`. Perhaps we could support only doing the left side of the equation?

**Comment by amilsted** [comment]
Yeah, it might be nice for someone to copy and paste an einsum expression and build the explicit tensor network from it (like one can currently do with `ncon_network()`). That way they can easily e.g. generate a picture of their network, or use it as a component of a larger network, etc.
