### ISSUE TITLE
Incomplete Tutorial Colab Notebook

### ISSUE THREAD

**Issue by sunbc0120** [google/TensorNetwork#409]
In the tutorial notebook of "Tensor Network Tutorial" > Section 2 > Avoid Trace edges, it says "One of the methods that".

I suspect it gonna introduce `contract_between`?

**Comment by Thenerdstation** [comment]
Good catch! Yes, I will fix that. Thanks for bringing this up!

**Comment by Thenerdstation** [comment]
Should be fixed now. Thanks again!
