### ISSUE TITLE
More flexible choice of which singuar values to keep?

### ISSUE THREAD

**Issue by gefux** [google/TensorNetwork#422]
Because this is my first issue, a little "hello" message:

> Hello everyone! First, thank you all for this great project. I agree that there is a desperate need for an agnostic tensor network package. I am doing a PhD in theoretical physics and although I coded a lot in my life, this is the first time I intend to actively participate in an OpenSource project. Because I am using tensor networks in an unconventional way for my research, I have an inherent interest in a general and flexible package. Speaking of which,...

Would we like a `relative: Optional[bool] = False` parameter in split_node() and split_node_full_svd() to make max_truncation_err relative to the biggest singular value?

Or maybe, even more general would be callable parameter that takes the list of singular values and returns a slice of which one to keep like:
`keep_sv: Optional[Callable[[List[float]], slice]] = None `

What do you think?
(I'd be happy to give it a go)

**Comment by MichaelMarien** [comment]
Hi and welcome!

Not sure about the need for a generic callable, but the relative criterium is definitely something I used before!

**Comment by gefux** [comment]
Closing, because I believe the `relative` option is sufficient (and now implemented). If anyone is keen on a more general svd cutoff, feel free to reopen.

**Comment by Thenerdstation** [comment]
:+1:

**Comment by Thenerdstation** [comment]
Is this a blocker for you? If you need it on the pip I can push a new verison today, other I'll wait until our blocksparse work is done in ~3-4 weeks.

**Comment by gefux** [comment]
It sort of is, but ~4 weeks is totally fine. Thank you very much for asking! :)
