### ISSUE TITLE
What to submit for a issue?

### ISSUE THREAD

**Issue by IllgamhoDuck** [google/TensorNetwork#423]
https://github.com/google/TensorNetwork/blob/8a4f8eb4b0a4a3e57022f63877ae903ef42cfe4c/tensornetwork/network_components.py#L314-L315

I'm trying to use the tensor network and testing it right now.
I just found that this line of code doesn't have protection.

So if I do ..
```
node = tn.Node(np.eye(2))
print(node) # __unnamed_node__
node.set_name(node)
print(node)
```
Type error occured not when I assign the name and occured when I try to print it out.
Because I sended the node instance to the self.name.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-cdce2f239ef3> in <module>
----> 1 print(node)

TypeError: __str__ returned non-string (type Node)
```

Is this a problem or not? Is this kind of protection needed?

```
assert type(self.name) == str, "the name should be string type"
```
I'm not sure about is this could be an issue or not so I just posted a question here.
I tried to look for a guideline but hard to get a sense of the scope of how far I could post or fix.
https://github.com/google/TensorNetwork/blob/master/CONTRIBUTING.md

**Comment by Thenerdstation** [comment]
Yeah, you could add that check. It would be in the `__str__` definition of the Nodes class. Since it's pretty straight forward, would you be interested in trying to do a PR for this?

**Comment by IllgamhoDuck** [comment]
@Thenerdstation Yes for sure. It's just one line of code so not really hard. Anyway, I'm digging on the codebase so for further I'll try to look at the protections and etc. I'm currently looking at the https://github.com/google/TensorNetwork/issues/292(algebraic operations for BaseNode).
