### ISSUE TITLE
Pytorch 1.4.0 breaks our build

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#427]
Needs to be investigated.

**Comment by IllgamhoDuck** [comment]
I'll try to look up for this

**Comment by MichaelMarien** [comment]
hi @IllgamhoDuck , not to stress you out, but will you get a chance to look at this in the near future? Would like to fix this myself otherwise, as otherwise these kind of things tend to get worse :).

**Comment by IllgamhoDuck** [comment]
Hi @MichaelMarien! Sure I would love to dig on it :) I'll try to look at this problem thanks for asking!
