### ISSUE TITLE
Fix graphviz 

### ISSUE THREAD

**Issue by iiskakov** [google/TensorNetwork#446]
Looks like this might be a bug:
![Screen Shot 2020-01-23 at 15 53 00](https://user-images.githubusercontent.com/45936496/73034027-9dfcde00-3df8-11ea-9954-02713ab0b498.png)

**Comment by Thenerdstation** [comment]
Yeah that's bad.

That function is pretty small, so a fix would be pretty straight forward for someone new.

**Comment by rafaelbalanquet** [comment]
Hello! I would possibly be interested (along with an amateur team). Is there any chance we can get more information about this issue? Thanks!
