### ISSUE TITLE
`auto` calls `branch` with incorrect number of parameters when n >= 5 and n < 7

### ISSUE THREAD

**Issue by Travmatth** [google/TensorNetwork#455]
https://github.com/google/TensorNetwork/blob/003fdc789afa006e08f12818ad76c5f31828aa69/tensornetwork/contractors/opt_einsum_paths/path_contractors.py#L243

The `branch` method accepts 5 parameters, but here is called with 4. This results in the `ignore_edge_order` parameter being passed into `branch` as `nbranch` and an inability to set `ignore_edge_order` when `n >=5 and n < 7`

**Comment by Thenerdstation** [comment]
Seems like a quick fix. Wanna do a PR?

**Comment by Travmatth** [comment]
Yup, doing now
