### ISSUE TITLE
Add tn.replicate_nodes

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#463]
This would be a simple wrapper around `tn.copy()`.

This new API would only accept a list of nodes and will return a list of copied nodes.

**Comment by dkreeft** [comment]
@Thenerdstation could you elaborate a bit more on what has to be done?

**Comment by Thenerdstation** [comment]
Basically this.
```
def replicate_nodes(list_of_nodes):
  nodes_dict, _ = tn.copy(list_of_nodes)
  new_nodes = [nodes_dict[node] for node in list_of_nodes]
  return new_nodes
```

+ Typing, unit testing, documentation.

**Comment by dkreeft** [comment]
Thank you, I am willing to try to implement this feature. @Thenerdstation could you assign this issue to me?

**Comment by Thenerdstation** [comment]
I don't assign issues to external users anymore, but you're welcome to do it!

**Comment by rckitson** [comment]
Hi @Thenerdstation this issue seems closed now with the method at `tensornetwork/network_operations.py:Line 157`

**Comment by Thenerdstation** [comment]
Yes you are correct. Thank you!
