### ISSUE TITLE
How to compute MLP with different input and output shapes

### ISSUE THREAD

**Issue by limapedro** [google/TensorNetwork#468]
Hi, I've been trying to get a layer with different input and output shapes, let's say an input shape 1024 with 256 as the output shape, in the colab page, it shows how to create a MLP layer with 1024, reshaped as 32x32 Tensor Network, but the output is also 1024 as the computation and a new reshape call, thanks in advance, this is a great project.

**Comment by Thenerdstation** [comment]
Thanks for the question! So to get the output shape you have size 256, you'll want your two "output" legs to have shape 8 and 16. As a rule, the product of the output legs gives you your new output size.
