### ISSUE TITLE
I am working to implement tensorlayer on pytorch but I am not sure about tf.vectorized_map

### ISSUE THREAD

**Issue by Xsurgeon** [google/TensorNetwork#478]
`class TNLayer(torch.nn.Module):
    """
    This is will define TNlayer 
    
    """
    def __init__(self):
        super(TNLayer,self).__init__()
        a_var    = torch.tensor(np.arange(128).reshape(8,8,2).astype('float'), requires_grad=True)
        b_var    = torch.tensor(np.arange(128).reshape(8,8,2).astype('float'), requires_grad=True)
        bias_var =  torch.zeros((8,8),dtype=torch.double)
    def forward(self, x):
        def f(input_vec,a_var,b_var,bias_var):
            # reshape to matreic instead of the vector 
            input_vec = torch.reshape(input_vec,(8,8))
            
            # create the network 
            a = tn.Node(a_var)
            b = tn.Node(b_var)
            x_node = tn.Node(input_vec.double())
            a[1]^x_node[0]
            b[1]^x_node[1]
            a[2]^b[2]
            
            c = a @ x_node
            result = (c@b).tensor 
            bias_var = bias_var

            return result+bias_var
        result= (lambda vec:f(vec,self.a_var,self.b_var,self.bias),x)
         #vectroize_map not sure from it how to be implemented 
        return torch.nn.functional.relu(result)
        `

**Comment by Thenerdstation** [comment]
The easiest thing to do in this case is to just treat the batch dimension as an extra leg on the input node. Then the 

```
def f(input_vec,a_var,b_var,bias_var):
        # reshape to matreic instead of the vector 
        input_vec = torch.reshape(input_vec,(BATCH_SIZE, 8, 8))
   
        # create the network 
        a = tn.Node(a_var)
        b = tn.Node(b_var)
        x_node = tn.Node(input_vec.double())
        a[1]^x_node[1]
        b[1]^x_node[2]
        a[2]^b[2]
        c = x_node @ a # Swap the order here to keep the batch dimension first.
        result = (c @ b).tensor 
```

Because this requires moving a lot of data, without compiling the computation graph I don't expect this to be significantly faster on pytorch.

**Comment by Thenerdstation** [comment]
For more complicated tensor networks you'll likely need some form of vmap/vectorized_map. All the more reason to try learning JAX. :)
