### ISSUE TITLE
Four node contraction gives inconsistent results

### ISSUE THREAD

**Issue by rdilip** [google/TensorNetwork#481]
I have a series of four tensors (two matrix product operators) that I want to contract in a slightly non standard way. The index conventions and contraction I want to perform is shown in the attached image.

![mpo_conventions](https://user-images.githubusercontent.com/9993319/76238190-ca957980-622f-11ea-9430-ddf8c5926366.jpg)

However, I get inconsistent results between iterations when comparing the contracted tensor. I've attached a MWE below. I'm somewhat at a loss for why this could be happening> I know it has nothing to do with the edge_order, as the ordering should be well defined in the call to get_all_dangling(), and in any case I tested by hardcoding an edge order. 

Would appreciate any help!

```python
import numpy as np
import tensornetwork as tn
a_shape = [(2, 1, 1, 2), (2, 2, 2, 2)]
lambda_shape = [(2, 1, 1, 2), (2, 1, 2, 4)]
A1 = [np.random.rand(*shape) for shape in a_shape]
Lambda = [np.random.rand(*shape) for shape in lambda_shape]

def process_mpos(mpo):
    tn_mpo = [tn.Node(i) for i in mpo]
    for i in range(len(mpo)-1):
        tn_mpo[i][-1] ^ tn_mpo[i+1][2]
    return tn_mpo

def mpo_on_mpo(mpoL, mpoR):
    L = len(mpoL)
    mpoL[0][1] ^ mpoR[0][2]
    for i in range(L-1):
        mpoL[i+1][1] ^ mpoR[i][0]
    mpoL[L-1][3] ^ mpoR[L-1][0]
    
    edge_list = []
    for i in range(L):
        edge_list.extend(mpoL[i].get_all_dangling())
        edge_list.extend(mpoR[i].get_all_dangling())
    output = tn.contractors.auto(tn.reachable(mpoL[0]), edge_list)
    return output

for i in range(10):
    A1_tn, Lambda_tn = process_mpos(A1), process_mpos(Lambda)
    out = mpo_on_mpo(A1_tn, Lambda_tn)
    A1_tn, Lambda_tn = process_mpos(A1), process_mpos(Lambda)
    out1 = mpo_on_mpo(A1_tn, Lambda_tn)
    print(np.allclose(out1.tensor, out.tensor))
```

**Comment by Thenerdstation** [comment]
`get_all_dangling` returns a `set`, so actually no there is no order guarantee at all.

https://tensornetwork.readthedocs.io/en/latest/tensornetwork.html#tensornetwork.get_all_dangling

**Comment by rdilip** [comment]
I'm a bit puzzled by this, since I tried replacing the loop adding to edge_list with the line `edge_list = [mpoL[0][0], mpoL[0][2], mpoL[1][0], mpoR[0][1], mpoR[1][1], mpoR[1][3]]`, and still get the same results. If the problem were the ordering being inconsistent, would this not fix the issue?

**Comment by Thenerdstation** [comment]
You can make your own `get_all_dangling` that would guarantee an order though.

```python
def custom_get_all_dangling(nodes):
  edges = []
  for node in nodes:
    for edge in node.edges:
      if edge.is_dangling():
        edges.append(edge)
  return edges
```

**Comment by rdilip** [comment]
Yes, that fixes it. Thanks. Out of curiosity, why are the dangling edges returned as a set, and not in (say) the order they're in the list of all edges?

**Comment by Thenerdstation** [comment]
Because the only constraint we set on the input of the function is that it is `iterable`. I don't think we'll change this API but I'm not against adding a `get_dangling_edges_ordered` which would just be the above code.
