### ISSUE TITLE
split_node_... routines crash during the second call 

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#494]
The following code crashes
```python 
import tensornetwork as tn
import numpy as np
tn.set_default_backend('tensorflow')
node1=tn.Node(np.random.rand(10,2,10))
tn.split_node_full_svd(node1,[node1[0], node1[1]], [node1[2]])
tn.split_node_full_svd(node1,[node1[0], node1[1]], [node1[2]]) #this raises a ValueError
```
with 
`ValueError: Edge 'Dangling_0' did not contain node '__unnamed_node__' on axis 0. node1: '__unnamed_node__', axis1: 0, node2: 'None', axis2: None`

The same is true for `split_node_qr` and `split_node_rq`. `split_node` is working though. Seems like a bug.

**Comment by Thenerdstation** [comment]
This is expected behavior. The edges get reset on `node1` after the split call.

**Comment by mganahl** [comment]
but why is it then crashing? The input to `split_node_full_svd` in the second line is just a regular `Node`, i.e. `node` with three normal, dangling `Edge`s.

**Comment by mganahl** [comment]
In any case, the behaviour is inconsistent since `split_node` works fine. I'll check what's going on.

**Comment by Thenerdstation** [comment]
Oh I see. Hm yeah that's strange. Let me look into it.

**Comment by mganahl** [comment]
found it. I had forgotten to call `node.fresh_edges` at the end out the routines. I'll make a fix
