### ISSUE TITLE
Memory size of class MPS

### ISSUE THREAD

**Issue by sebgrijalva** [google/TensorNetwork#498]
Hello, I hope this is the correct place to ask this, if not please tell me the more proper route:

I'm trying to understand the memory size of the MPS objects , so I wrote the following script, using the pympler package (similar results are obtained by repeatedly using `sys.getsizeof()`):

```python
!pip install tensornetwork
!pip install pympler 

import numpy as np
import tensornetwork as tn
from tensornetwork import matrixproductstates as mps
from pympler import asizeof
import matplotlib.pyplot as plt

dimensions = [2,3,4,5] 
ranks = range(2,40)

for phys_dim in dimensions:
    bond_dim = 2 # constant
    memory = []
    
    for rank in ranks:    
        # build the mps with random entries:
        mpstate = mps.finite_mps.FiniteMPS.random(d = [phys_dim for _ in range(rank)], D = [bond_dim for _ in range(rank-1)], dtype = np.float32)
        
        # connect the edges in the mps
        connected_edges = [mpstate.nodes[k][2] ^ mpstate.nodes[k+1][0] for k in range(rank-1)]
        
        # record memory usage of mps
        memory.append(asizeof.asizeof(mpstate) + asizeof.asizeof(connected_edges)) 
    
    plt.plot(ranks, memory,'.')

plt.show()

```
Basically for each dimension I sweep over increasing ranks to find out how will the memory size scale. However, I get the same result for any (physical) dimension. This seems odd to me, so I want to know if this is somehow related to how the class is built, or if it's a mistake on my part.

Thanks for any feedback!

**Comment by mganahl** [comment]
Thanks for your question! Are you interested in the memory size of the complete `FiniteMPS` object (including memory used up by the infrastructure), or just in the memory requirements of the MPS tensors? The latter is typically the dominant contribution. I am not familiar with `pympler`, but there is simple way of obtaining byte-size of `np.ndarray`. If you are interested in the memory size of the MPS tensors, then here is a simple code that achieves this for the case of our `'numpy'` backend:
```python 
import numpy as np
import tensornetwork as tn

import matplotlib.pyplot as plt

def get_mps_size(mps):
    assert mps.backend.name=='numpy'
    nbytes = 0
    for node in mps.nodes:
        nbytes += node.tensor.nbytes #works only for numpy
    return nbytes

dimensions = [2,3,4,5] 
ranks = range(2,40)

    
for phys_dim in dimensions:
    bond_dim = 2 # constant
    memory = []
    for rank in ranks:    
        mps = tn.FiniteMPS.random(d = [phys_dim for _ in range(rank)], D = [bond_dim for _ in range(rank-1)], dtype = np.float32)
        memory.append(get_mps_size(mps))
    plt.plot(ranks, memory,'.', label=f'D={bond_dim}, d={phys_dim}')
plt.legend()
plt.xlabel('N')
plt.ylabel('bytes')
plt.show()
```
Let me know if this solves your problem!

**Comment by sebgrijalva** [comment]
Yes, thanks a lot! This is exactly what I was looking for.
