### ISSUE TITLE
measure_two_body_correlator causing UnboundLocal Error

### ISSUE THREAD

**Issue by co9olguy** [google/TensorNetwork#527]
See below for a MWE. From inspecting the source code, I think the issue is due to the fact that the variable ``ls`` is only created if there are valid ``left_sites``, but it is implicitly assumed to exist later on in the function body.

The docstring is a big ambiguous, so I hope I'm passing the arguments as intended.
```
import tensornetwork as tn
import numpy as np

tensor = np.array([1.0, 0]).reshape([1,2,1])
nodes = [tn.Node(tensor) for _ in range(3)]
mps = tn.matrixproductstates.finite_mps.FiniteMPS(nodes)
op = np.diag([0.5, -0.5])

mps.measure_two_body_correlator(op, [op], 0, [1])
```

**Comment by Thenerdstation** [comment]
@mganahl can you take a look into this?

**Comment by mganahl** [comment]
thanks @co9olguy for posting the issue. I'll have a look!

**Comment by mganahl** [comment]
This is a bug. I submitted a PR to dfix it,and also improve the docstring. Thanks for pointing this out!

**Comment by co9olguy** [comment]
Thanks @mganahl @Thenerdstation for the quick fix! :smiley:
