### ISSUE TITLE
Add PyTorch backend.

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#53]
Once https://github.com/google/TensorNetwork/pull/52 is submitted, it would be nice to add a pytorch backend. 

TF eager and pytorch are very similar, so someone could use the `TensorFlowBackend` as an example.

**Comment by MichaelMarien** [comment]
Hi,

would be happy to take it up, as you said, should be quite similar to the tf-backend. Quite a busy July though, so might only finish it in Aug. Is this very urgent?

**Comment by Thenerdstation** [comment]
Not urgent at all! And we would love to have you as a contributor.

It should be fairly straightforward with the exception of some weird shape only functions, specifically `prod` and `concat`. I'll be sure document it better before you get started in August.

If you get stuck or need any help, feel free to email me! chaseriley@google.com

**Comment by MichaelMarien** [comment]
Just remembered PyTorch still does not have full support for complex numbers. Do we expect this to be blocking in the future?

**Comment by Thenerdstation** [comment]
There are still use cases for exclusively real valued tensors, especially in ML. I'd say it's still worth it.

**Comment by Thenerdstation** [comment]
We'd have to explicitly exclude some tests, but I don't think we have that many.

**Comment by MichaelMarien** [comment]
I added a first try / progress in PR #165 , if you have time, feel free to give comments.

**Comment by Thenerdstation** [comment]
We'll push 0.0.6 tonight with your Pytorch backend!

**Comment by Thenerdstation** [comment]
0.0.6 is live! Just do `pip upgrade tensornetwork` and you should be good to go
