### ISSUE TITLE
signature of node is always default as -1

### ISSUE THREAD

**Issue by refraction-ray** [google/TensorNetwork#530]
I am wondering if this is the expected behavior for creating nodes since signature should be somewhat the unique id for the nodes. By default, all nodes created by tn.Node has signature -1, and this will have impact on several other utilities at least on `tn.to_graphviz` which depends on signature to draw different nodes. 

```python
s = [tn.Node(np.array([[1.0], [0]], dtype=np.complex64), name="l"),
     tn.Node(np.array([[1.0], [0]], dtype=np.complex64), name="r"), ]
print(s[0].signature, s[1].signature) # -1, -1
tn.to_graphviz(s)
```
The above snippet shows diagram with only one node instead of two due to the signature issue.

My suggestion: within ``__init__`` of tn.Node, the default signature should be generated as: 1. based on node name if set 2. a default global unique id if no node name is specified (perhas via class attr of tn.Node).

**Comment by refraction-ray** [comment]
This issue is also the reason for https://github.com/google/TensorNetwork/issues/446

**Comment by mganahl** [comment]
thanks for the post! I'll have a look into it

**Comment by Thenerdstation** [comment]
Yeah signature was a long forgetting attribute that was intended for a feature that was never built. Really we should just get rid of every use of `signature` and just use `id(node)` instead for graphviz.
