### ISSUE TITLE
Plans on further extending ops in backend

### ISSUE THREAD

**Issue by refraction-ray** [google/TensorNetwork#543]
For now, ops in basebackend seem to be enough to cover basic ops in tensor network within this package.

However, for downstream developers who build packages on top of TensorNetwork and also want to maintain the multiple backend feature of TensorNetwork , the ops in current backend setup may  be not enough.  For example, sin, cos, lg, expm, various matrix decomps might be necessary for applications with tensor networks.

Ultimately, it would be very nice if one can write any code with `tn.backend.ops` and run the codes using different backends with auto differentiation and computation graph tracking still enabled. A somehow unified world of machine learning programming, ahh.

Although this goal may be too big or too far away, my real question is do you have any plans to extend the ops covered in base backend? Or do you think it is better to leave other ops for downstream developers to implement in their own package since these ops don't play roles in Tensor Network package itself.

PS. there are some wrong docstrings in base_backend.py due to copy paste, like https://github.com/google/TensorNetwork/blob/8a88b3f499c1ef75826996a9676480d74a44368d/tensornetwork/backends/base_backend.py#L432, https://github.com/google/TensorNetwork/blob/8a88b3f499c1ef75826996a9676480d74a44368d/tensornetwork/backends/base_backend.py#L419

**Comment by Thenerdstation** [comment]
Additional ops are being added on a need basis on our end, but we could accept PRs to extend the functions if some downstream application needs it and it's not too obscure.

Trying to unify all ML libraries is very out of scope of this library. 

And yes we should fix those bad doc strings... PRs are welcome!

**Comment by refraction-ray** [comment]
In my setup, I even included some infrastructure of jax like `vmap`, `jit`, `grad` as ops for universal backend, for example the following is the corresponding interface for tf backend.
https://github.com/refraction-ray/tensorcircuit/blob/b416e205c584976d8540bed0f7195cbd763d7172/tensorcircuit/backends.py#L143-L173 .

In this way, we could write code with jit and AD while keeping multiple backends feature. What do you think about these ops of backends? Are they things to be included in tensornetwork or are they too fancy or fragile or irrelevant to be considered here?

**Comment by Thenerdstation** [comment]
I think these are a little out of scope with this project. I was ok with adding `cos`, `sin` etc because it's pretty common to want to generate Tensors based on these attribute, but things like `jit` and `grad` are too specific to just Jax and Tensorflow (how would this relate to a numpy backend?). 

I applaud you efforts of building a unified ML framework, but that would probably be best for a different library.
