### ISSUE TITLE
tn.split_node() doesn't work with TF 2.x

### ISSUE THREAD

**Issue by jaeyoo** [google/TensorNetwork#545]
The following code works with TF 1.15, but shows errors with TF 2.x

**Code**
```python
import tensornetwork as tn
tn.set_default_backend("tensorflow")

dense_tensor=np.array([[0.8,0.0,0.0],[0.0,0.12,0.0],[0.0,0.0,0.08]])
a = tn.Node(dense_tensor)
u, vh, _ = tn.split_node(a,
                         left_edges=a[:1],
                         right_edges=a[1:])
```

**Error**
```
TypeError: len is not well defined for symbolic Tensors. (Shape_23:0) Please call `x.shape` rather than `len(x)` for shape information.
```

Could you give me any help please?

**Comment by refraction-ray** [comment]
I can run your code demo successfully with no error, with tensornetwork HEAD and tensorflow 2.1

**Comment by mganahl** [comment]
thanks for the post, I'll have a look!

**Comment by Thenerdstation** [comment]
What is the version we currently test with in our Travis build? Ideal we should always aim to support the latest version of tensorflow, as trying to support all of TFs releases just isn't going to happen....

**Comment by mganahl** [comment]
we're testing tensorflow 2.0.0 currently

**Comment by Thenerdstation** [comment]
And I ran it with the 2.0.0a build and the above code also worked fine for me.

**Comment by mganahl** [comment]
It also works for me using tensorflow 2.1.0. Can you print out the tensorflow version as well?

**Comment by jaeyoo** [comment]
@Thenerdstation @mganahl @refraction-ray Sorry folks, I realized that I am using different versions. There is no error at all. Thank you for cross-checks! 👍
