### ISSUE TITLE
[Question] Compatibility with tf lite for embedded devices TensorNetwork?

### ISSUE THREAD

**Issue by gaceladri** [google/TensorNetwork#547]
I am looking for incorporate your Keras example as a Layer in my Keras model. I am thinking if it is compatible with tf.lite and methods like model quantization and so on. Are you aware about this? Do you know if it could work?

**Comment by Thenerdstation** [comment]
So our tensorflow backend basically only calls `matmul`, so it *should* just work, but quantization can be finicky and we've never tried it.

**Comment by gaceladri** [comment]
Thank you for your answer @Thenerdstation . I will try to quantize it to 8/4 bits with tf lite in the next week or so.
