### ISSUE TITLE
Add pure Numpy backend

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#55]
Add a pure numpy backend once https://github.com/google/TensorNetwork/pull/52 is merged.

**Comment by stavros11** [comment]
I have some progress on this, it seems that it should not be much different from the tensorflow backend. What is the current plan? Are we waiting for feedback on #52 or do we need the numpy to change the tests? Currently I can test my numpy locally by modifying `tensornetwork_test.py` (changing some `tf.ones` to `np.ones` and removing the eager related tests) but we will probably have general backend-independent tests at some point.

**Comment by Thenerdstation** [comment]
Awesome!

Just wait for https://github.com/google/TensorNetwork/pull/52 to be merged. Then we can merge your numpy backend and change the tests.

**Comment by Thenerdstation** [comment]
If you want to do some stuff today, you can replace the `tf` with `np` when possible and move the tensorflow specific tests into the graphmode test file.
