### ISSUE TITLE
Some doc links to github yield error

### ISSUE THREAD

**Issue by zaqqwerty** [google/TensorNetwork#550]
The "Edit on GitHub" links in the top right of some doc pages yield 404 errors when followed, for example [tn.Node](https://tensornetwork.readthedocs.io/en/latest/stubs/tensornetwork.Node.html) and [tn.contractors.optimal](https://tensornetwork.readthedocs.io/en/latest/stubs/tensornetwork.contractors.optimal.html#tensornetwork.contractors.optimal).

The links at the top of list pages work, for example [common functions](https://tensornetwork.readthedocs.io/en/latest/network.html) and [contractors](https://tensornetwork.readthedocs.io/en/latest/contractors.html).

Possibly those are meant to be links to edit the doc pages themselves, rather than the source code?

**Comment by Thenerdstation** [comment]
Huh, weird. The Edit on Github link is auto generated, so I'd have to investigate how that is setup.
