### ISSUE TITLE
conflict between pickle and thus multiprocessing with backend module assignment

### ISSUE THREAD

**Issue by refraction-ray** [google/TensorNetwork#553]
In the current implementations of backends, we have the following thing:
```python
class SomeBackend():
    def __init__(self):
        self.np = numpy
```

Note numpy is a module, and of course such backend is included as one attr of `tn.Node`. 

The effect of such design is you will fail when you try:

```python
from multiprocessing import pool
def f(x): 
    return tn.Node(np.eye(x))
with Pool(3) as p:
        print(p.map(f, [1, 2, 3]))
```
the error is `can't pickle module objects` which is induced ultimately by `numpy` attr in backend class. This is due to the lack of ability to pickle modules in python. To verify this, one can either comment ``self.backend=backend`` in network_components or change all ``self.numpy`` to plain ``numpy`` in numpy_backend py. There will be no error for both modifications.

It is worth noting that other multiprocessing libraries such as pathos has no problem to interact with TensorNetwork as its core pickle library is dill which is more powerful. However, you may want to interact TN with other libraries with python builtin multiprocessing baked in. In such cases, TN fails the task.

Maybe we should just use plain ``np``, ``tf`` in backend files instead of ``self.np`` to overcome this?

**Comment by Thenerdstation** [comment]
I believe we did it this way because we want to make sure we always support users who don't have all of the supported backends installed. If you just have a plain `import tensorflow` at the top instead of in side the class, you'll immediately crash upon importing TN if you do not have TF installed.

**Comment by Thenerdstation** [comment]
If you have a workaround that solves both your issue and the import issue mentioned above, we'd gladly accept a PR!

**Comment by Thenerdstation** [comment]
Aw yes it's all coming back to me as for why we did this. Checkout the discussion on https://github.com/google/TensorNetwork/pull/241#discussion_r322351287

Its a weird issue with how our build system works internally. If some files in a module aren't imported when the module itself is imported, then those files won't be included in the file `.par` package and you'll hit those runtime errors seen in that discussion.

**Comment by mganahl** [comment]
We could try to  assign imported modules to global variables like so:
```python 
class Backend:

  def __init__(self):
    global jax
    try:
      import jax as jaxlib
    except ImportError:
      raise ImportError("jax not installed")
    jax = jaxlib


if __name__ == "__main__":
  backend = Backend()
  b = jax.numpy.zeros(10)
  print(b)
```
This could be potentially confusing though because `jax` will be at global scope even though the user never imported it.

**Comment by mganahl** [comment]
that would fix the pickle issue

**Comment by mganahl** [comment]
actually, wasn't it set up this way in the first place?

**Comment by Thenerdstation** [comment]
No we definitely never had a global, but this might work. 

My main concern is that the `JaxBackend` inherits the `NumpyBackend`, but we just override the numpy operations via the `self.np`. I'm not sure the global here would behave correctly in that situation.

**Comment by Thenerdstation** [comment]
(I'm also not against just biting the bullet and separating these two backends.)

**Comment by mganahl** [comment]
I also think we would need to abandon inheritance of `NumPyBackend` in `JaxBackend` , though
this would be really a minor change (mostly search and replace)

**Comment by MichaelMarien** [comment]
Are we sure we cannot fix the build such that the PR in #241 works? Feels like that is the nicest way to separate the concerns. @Thenerdstation do you remember a minimal breaking example that addresses the core issue? Would be interested to give it a try?

**Comment by Thenerdstation** [comment]
Well no I can't easily change the Google build system. :)

If I remember correctly, the issue stemmed from trying to import the `decompositions` file, but those no longer import their backend libraries (they get them passed in via the `self.np`/`self.tf`).

Honestly, this my be the one time I allow `global` in the codebase. I think a variation of martin's solution is the right one.

**Comment by MichaelMarien** [comment]
Well, clearly I have no clue about the Google build system, but I'm gonna go ahead and assuming it's quite good :). Then, I feel like there is a clean way it allows us to do what we want. Problem is there's no easy way to test/experiment with it for me I guess? Must admit I really don't like the global thing, but if it deblocks the OP, it's worth the effort.

**Comment by Thenerdstation** [comment]
agreed. And globals are OK in this instance since imports at the top are just implicitly globals anyway. Modules are also immutable structures, so they are basically considered constants.

I'm a bit swamped at the moment, so would either @mganahl or @MichaelMarien be interested in heading this?

**Comment by MichaelMarien** [comment]
Is there any way we could test whether what we do breaks the Google system?

**Comment by Thenerdstation** [comment]
I can test it easily once you have a PR.

But basically as long as the only dynamic importing we do is external libraries (scipy, jax, numpy, tensorflow, etc), you should be good to go

**Comment by Thenerdstation** [comment]
Also michael it's good to hear from you! Glad you're still interested in the library. :)

**Comment by MichaelMarien** [comment]
Trying to keep up with just understand @mganahl 's PR avalanche has kept me from actually contributing :D

**Comment by Thenerdstation** [comment]
Yeah he does a lot now haha.

So was that a yes on the PR?

**Comment by MichaelMarien** [comment]
I'll take a look on Friday

**Comment by Thenerdstation** [comment]
Nah it's ok then. I'll just do it tonight while I'm writing tutorials.

**Comment by refraction-ray** [comment]
I am still confused essentially which part will fail in google internal build system, otherwise I might have some ideas on the refactoring of backend design. I am not very into the global thing and actually I don't know what will fail when global keywords nonexist.

**Comment by mganahl** [comment]
Has this been resolved?

**Comment by Thenerdstation** [comment]
Yes as of the latest release that I literally just pushed lol. https://github.com/google/TensorNetwork/releases/tag/0.3.1
