### ISSUE TITLE
switch to using a single instantiation of backend objects

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#561]
We're currently using a new backend object every time we create e.g. a `Node`. 
To facilitate implementation of DMRG into backends like jax or tensorflow we should
switch to instantiating only one object per backend, and then keep reusing it .

**Comment by mganahl** [comment]
I'm already using this experimentally. Could submit a PR quickly

**Comment by Thenerdstation** [comment]
+1 sgtm. All of the nodes should share the same backend object
