### ISSUE TITLE
consistent formatting

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#567]
For some reason, yapf on my platform (MacOS Catalina 10.15.3) produces formatting that is inconsistent with other contributor's formats (I use py-yapf on emacs).

Example:  `slice` will get formatted on my laptop like this
```python 
class TensorFlowBackend(base_backend.BaseBackend):
  """See base_backend.BaseBackend for documentation."""

  ...
  def slice(self, tensor: Tensor, start_indices: Tuple[int, ...],
            slice_sizes: Tuple[int, ...]) -> Tensor:
    if len(start_indices) != len(slice_sizes):
      raise ValueError("Lengths of start_indices and slice_sizes must be"
                       "identical.")
    return tf.slice(tensor, start_indices, slice_sizes)
```

while in the code base it's
```python 
class TensorFlowBackend(base_backend.BaseBackend):
  """See base_backend.BaseBackend for documentation."""

  ...
  def slice(self, 
            tensor: Tensor, 
            start_indices: Tuple[int, ...],
            slice_sizes: Tuple[int, ...]) -> Tensor:
    if len(start_indices) != len(slice_sizes):
      raise ValueError("Lengths of start_indices and slice_sizes must be"
                       "identical.")
    return tf.slice(tensor, start_indices, slice_sizes)
```

**Comment by MichaelMarien** [comment]
@mganahl , @Thenerdstation what about introducing an opinionated formatter like black?

**Comment by MichaelMarien** [comment]
Black would not allow a 2-space indent I believe, might need to look for an alternative tool.

**Comment by mganahl** [comment]
did yapf change the name of its "chromium" style? I reinstalled yapf and it gives me a key error

**Comment by mganahl** [comment]
they actually did

**Comment by mganahl** [comment]
@Thenerdstation would you mind to reinstall yapf and check how the above snippets gets formatted on your laptop? Maybe its just a matter of yapf versions. Thanks!

**Comment by MichaelMarien** [comment]
Whoops didn't realise we're using yapf :D

**Comment by mganahl** [comment]
lol, no problem! Maybe we should just yapf the whole repo once to get a consistent style

**Comment by MichaelMarien** [comment]
Might be worth mentioning this in the contributing guidelines and ask people to do this before making a PR?

**Comment by Thenerdstation** [comment]
Speaking of which, we should revamp the README now too.

**Comment by Thenerdstation** [comment]
Closing since #572 is already merged.
