### ISSUE TITLE
tensorflow 2.2.0 breaks our build

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#586]
It seems that tensorflow 2.2.0 breaks our build, at least it does so on my platform.
We should also bump versions of jax and jaxlib in requirements_travix.txt, there was a bug
in jax.numpy.qr on macOS that got only recently fixed.

**Comment by Thenerdstation** [comment]
Wow TF breaks their API a lot.

I though our Travis build uses >= for the Jax versions. Does it not?

**Comment by mganahl** [comment]
you're right travis uses >=.

It's weird, the API for tf.random.uniform didn't actually change, but I still get a linter complaing
