### ISSUE TITLE
Outer product for operators

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#603]
#602 brought up an interesting point of defining operators based on the outerproduct of several smaller tensors. The issue is the normally an operator has its "input axes" defined as the first N axis, and the "output axes" are the last N axes. When dot producting tensors together, the input and output axes are weaved together, forcing a user to do a nasty `reshape` or `reorder_edges` before the tensor can be used for things like the `FiniteMPS` class.

I propose a new method `tn.operator_outer_product(list_of_nodes)` that would do the outer product but maintain the edge order thats expected for operator tensors.

**Comment by gevenbly** [comment]
The function you are describing sounds like a version of the numpy `kron` (kronecker tensor product) but for nodes (which also produces the edge order that's expected for operator tensors). The name of the new method could be chosen to reflect this.

**Comment by Thenerdstation** [comment]
Good idea. I like that much better.

**Comment by sr33dhar** [comment]
So here again, is the idea to use kron and then reshape?
Thank you

**Comment by Thenerdstation** [comment]
The idea is that kron would do the reshape for you automatically

**Comment by Thenerdstation** [comment]
Maybe something like `tn.operator_kron` would be a better name since `kron` doesn't do the reshaping magic.

**Comment by sr33dhar** [comment]
I see. Thank you.

I understand the idea of expressing 2 qubit gates as tensor products, (or the sum of tensor products for entangling gates), but I am having trouble understanding how tensor products and reshaping can give equivalent results. 

Is the idea just seeing if it works, and since it does, accepting it?

**Comment by Thenerdstation** [comment]
I guess its actually transposing and not reshaping.

You can see this for yourself pretty easily just with numpy.

```python
X = ...
Y  = ...
A = np.tensordot(X, Y, axes=0).reshape((2, 2, 2, 2)).transpose([0, 2, 1, 3])
B = np.kron(X, Y).reshape((2, 2, 2, 2))
np.assert_allclose(A, B)
```

**Comment by gevenbly** [comment]
Hi Chase, 
the kron function is widely used in the physics community as the standard method for defining lattice Hamiltonians (not only by people interested in tensor networks, but for many other kinds of numerical physics). For instance, the standard way to construct the Heisenberg model is:  
`hloc = (np.kron(sX,sX) + np.kron(sY,sY) + np.kron(sZ,sZ)).reshape(2,2,2,2)`
So, if _tensornetwork_ adopted a similar name and syntax, it would be easily understood by many physicists.

**Comment by Thenerdstation** [comment]
Sure! So should I change it to only accept 2 inputs then? Also, how should we handle the legs? Right now i keep then separated but `kron` effectively flattens them

**Comment by gevenbly** [comment]
Having an arbitrary number of inputs is very useful, as is keeping the legs separate (i.e. returning a tensor rather than a matrix). In my previous numpy code I would typically write a wrapper for kron, called something along the lines of `tkron`, that would incorporate these useful features. The function should also be able to handle the case where one or more of the inputs is a tensor, i.e. the tensor product of a 2-site operator (represented as a 4-index tensor) with a 1-site operator (represented as a matrix).

**Comment by gevenbly** [comment]
I suppose that it could also accept an optional argument which determined whether to do the reshape or not (both cases are useful sometimes)

**Comment by Thenerdstation** [comment]
The non-reshaped version is already supported by `tn.outer_product`, so no need for a flag.

**Comment by Thenerdstation** [comment]
Glen if you could also take a look at #606 your comments would be appreciated.

**Comment by gevenbly** [comment]
kron and outer_product typically have a different order on the final indices though. The kron of a 2-site operator `T_ijkl`  with a 1-site operator `R_mn` will produce a 3-site operator `Q_ijmkln`, which is the desired index order for the tensor product of operators. In my understanding, doing this with outer_product would require a separate `transpose` of the output to produce the desired order.

**Comment by Thenerdstation** [comment]
Correct.

**Comment by Thenerdstation** [comment]
Oh my bad I miss read reshape and transpose.

**Comment by Thenerdstation** [comment]
I think we'll keep `kron` to not support flattening the edges/reshaping the tensor to a matrix. If a user wants it we can always add it later.
