### ISSUE TITLE
Flat flows and flat charges in blocksparse

### ISSUE THREAD

**Issue by gevenbly** [google/TensorNetwork#613]
Hi @mganahl, I believe there are some issues with `.flows` `._flows` and `.flat_flows` in blocksparse. Consider the following example:
 
```
# define tensor
i0 = Index(U1Charge([-1,1]), flow=False)
i1 = Index(U1Charge([-1,0,1]), flow=False)
i2 = Index(U1Charge([-1,0,0,1]), flow=False)
i3 = Index(U1Charge([-2,2]), flow=True)
i4 = Index(U1Charge([-2,0,2]), flow=True)
i5 = Index(U1Charge([-2,0,0,2]), flow=True)
T0 = BlockSparseTensor.random([i0,i1,i2,i3,i4,i5]) 
# do transposition
T1 = T0.transpose([2,3,0,1,5,4]).reshape([8,2,3,12])
```
Then when I examine `T1` the following is returned:
```
# T1._order == [[2, 3], [0], [1], [5, 4]]
# T1.flat_order == [2,3,0,1,5,4]

# T1.flows == [[False, True], [False], [False], [True, True]]
# T1._flows == [False, False, False,  True,  True,  True]
# T1.flat_flows == [False, False, False, True, True, True]

# T1.charges == [[i2,i3],i0,i1,[i5,i4]]
# T1._charges == [i0,i1,i2,i3,i4,i5]
# T1.flat_charges == [i0,i1,i2,i3,i4,i5]
```
So `T1._flows` and `T1.flat_flows` are exactly the same (similarly for the charges); they both give the flows before the lazy transposition and reshape. Is this intended behavior? It seems that it should instead be:
```
# T1.flat_flows == [False, True, False, False, True, True]
# T1.flat_charges == [i2,i3,i0,i1,i5,i4]
```
such that  `T1.flat_flows` is a flattening of  `T1.flows` rather than of `T1._flows`, which would be a useful attribute to have defined.

**Comment by mganahl** [comment]
thanks @gevenbly! This is indeed intended behaviour, though it should be changed. I don't recall the exact problem, but both properties were used to ensure backwards compatibility with earlier code versions. At this point though they have become redundant, so we should remove them. 
My suggestion is to remove them completely. Would you like instead to support the above described behaviour?

**Comment by gevenbly** [comment]
Supporting the behavior I describe above would be very useful, as the `flat_flows` and `flat_charges` are something that I would otherwise have to build myself each time I needed them (which is quite often).

**Comment by mganahl** [comment]
sounds good, I will change it so that it has the desired behaviour.
