### ISSUE TITLE
Unintended lazy transposition in blocksparse 

### ISSUE THREAD

**Issue by gevenbly** [google/TensorNetwork#614]
Hi @mganahl , I have encountered some weird behavior with the transposition in blocksparse. Consider the following code:
```
ham = BlockSparseTensor.random([i0,i0,i0,i1,i1,i1]) 
hamT = ham.conj().transpose([3,4,5,0,1,2]) 
```
If I check the orders then the following is returned:
```
# ham._order == [[0],[1],[2],[3],[4],[5]]
# hamT._order == [[3],[4],[5],[0],[1],[2]]
```
As expected, this indicates that `hamT` is subject to a lazy transposition (and `ham` is not). However if I now do:
```
matrix = ham + hamT
```
Then when I recheck the order I now get:
```
# ham._order == [[3],[4],[5],[0],[1],[2]]
```
So, in when adding the two tensors together, blocksparse has done a transposition of `ham` in memory, even though `ham` was never a lazily transposed tensor. I think I understand why this is the case, but do not think that this should be allowed behavior from blocksparse. One reason is that it could result in the code transposing tensors in memory much more than is necessary. And on a conceptual level, I do not think blocksparse should be doing transpositions (in memory) on tensors where no transposition call was ever issued (i.e. the lazy transpose should delay evaluation of a `.transpose` operation until necessary, but should not decide on its own to start shifting in memory tensors where `.transpose` was never called to begin with).

I think that binary operations on tensors, e.g. `ham + hamT`, should instead ask: has any tensor been subjected to a lazy transposition that has not yet been evaluated? If yes, then do the transposition explicitly before performing the binary operation.

**Comment by mganahl** [comment]
Thanks @gevenbly! That is my bad. I'll fix this such that `hamT` is transposed in memory instead of `ham`

**Comment by mganahl** [comment]
@gevenbly there is the case though where both of the two operands have been lazily transposed. I think it is not desired in this case that both operands get transposed since one transposition is enough. I think in this we should pick one of the two and transpose only this one.

**Comment by gevenbly** [comment]
Thats a good point; I agree that in the addition of two lazily transposed tensors (with different orders) that only one explicit transpose should be done. Although doing both would probably not be so bad, as all lazily transposed tensors usually get evaluated at some point.  Thanks!
