### ISSUE TITLE
Blocksparse not evaluating scalar products properly

### ISSUE THREAD

**Issue by gevenbly** [google/TensorNetwork#615]
Hi @mganahl , I am having issues when trying to contract networks that evaluate to a scalar. For example defining:
```
i0 = Index(U1Charge([-1,1]), flow=False)
i1 = Index(U1Charge([-1,1]), flow=True)
T0 = BlockSparseTensor.random([i0,i1]) 
```
then evaluating `ncon([T0,T0],[[1,2],[2,1]])` produces an error. It this specific instance, I can instead evaluate the network as `c = trace(T0 @ T0)`, however `c` is returned as some kind of weird rank-0 blocksparse tensor rather than a scalar as expected. Evaluating `c.todense()` produces an empty array, but taking `c.data` gives the correct scalar (although the .data field is not something the user should ever have to touch). Can blocksparse `trace` be fixed to return a scalar? And also blocksparse `ncon` fixed to work with closed tensor networks? (i.e networks that contain no dangling edges)

On a related note, I see that the numpy version of `ncon` returns a length-1 numpy array when contracting closed tensor networks. I would strongly advocate that the return from evaluating a closed tensor network (no dangling edges) should always be a plain scalar, regardless of the types of the tensors involved.

**Comment by mganahl** [comment]
Hey @gevenbly, regarding your second point, for me`ncon` is returning an unsized object for contraction of a closed network. Could you give an example of when it returns a length-1 array?

tahnks!

**Comment by mganahl** [comment]
In general  I think it's better to have `ncon` return a `Tensor` object rather than a python number, also for closed networks.

**Comment by gevenbly** [comment]
Hi @mganahl , if I set `a = np.random.rand(10,10)` and then evaluate `b = ncon([a,a],[[1,2],[2,1]])` then the type of `b` is a numpy array, but you are correct in that it is an unsized object rather than a length-1 array.

Is there a reason why you want ncon to return a 0-rank tensor for closed networks? (or, more generally, why 0-rank `Tensor` objects should even exist?) I do not see the benefits to this, and this presents as very unexpected behavior for me (based on experience with functions like the `np.dot` of two vectors or the `np.trace` of a matrix, which produce scalars rather than numpy arrays). It would make more sense to me blocksparse trace and ncon replicated this behavior. Furthermore, mathematically speaking, the trace is of a matrix is defined as the sum of the elements along the main diagonal, so this should logically be an object of the same type as the elements themselves.

**Comment by mganahl** [comment]
Currently, we're sticking with the conventions of `tensordot`, which returns a rank-0 array. I am hesitant to force backend tensors into python scalars because I'm not sure how this will interact with e.g. jitting in jax. I'll have a look into it.

**Comment by gevenbly** [comment]
The `tensordot` convention is not so bad, since the unsized arrays behave identically to scalars and are automatically converted by to scalars under common operations (e.g. +,-,*,/). Although, switching from my numpy `ncon` to the tensornetwork numpy `ncon` did cause some of my codes to crash, where I was using things like `fprintf` which expected a scalar input. If you are keeping 0-rank blocksparse arrays, then is there a way to make them to similarly autoconvert to scalars under common operations and print statements?

I am think that, for some tensor `A`, things like the following code should work regardless of the backend:
```
energy = trace(ham @ rho)
A = A / energy
```
It would otherwise be quite a pain if the blocksparse needed an additional conversion step to work (as well as being a point of confusion for new users).

**Comment by gevenbly** [comment]
Also, if keeping the 0-rank blocksparse arrays, then I think it could be useful to add a `.item()` method to blocksparse, which would enable the code to be consistent between numpy and blocksparse, e.g. if `A` results from the ncon contraction of a closed network, then `A.item()` is always a scalar regardless of backend. This could also resolve any objections that I previously had.

**Comment by mganahl** [comment]
I absolutely agree that `*/+-` have to be supported seamlessly.  I'll add support for those operations to the `BlockSparseTensor`. I'm have actually already added `item()`, I just need to submit a PR

**Comment by mganahl** [comment]
The problem though is that soem backend tensors do not have `item()` available (e.g. tensorflow).

**Comment by mganahl** [comment]
@gevenbly  what's your opinion charges for scalar `BlockSparseTensor`s? Right now `tensordot` returns a `BlockSparseTensor` of rank 0 for the case of an inner product. This tensor has no charges and thus also no charge information. I think it's inconsistent but I'm OK with letting it go for now.

**Comment by gevenbly** [comment]
I think that it has to be this way. For the case of blocksparse tensors there is a significant difference between having a rank-0 tensor and having a rank-N tensor with index dims equal to 1 (whereas there is no significant difference for numpy arrays). I would think that trying to put charge or flow information on a rank-0 blocksparse tensor would lead to inconsistent behavior (which is one of the reason that I advocate that rank-0 blocksparse tensors should not be allowed).

**Comment by mganahl** [comment]
sounds good. In this case let's leave it as it is for now to have consistent behaviour between the backends, and I'll add operational support for `+-*/` for the case of a rank-0 `BlockSparseTensor`.

**Comment by gevenbly** [comment]
okay, sounds good. It case you have not done so already, could you also please fix the `to_dense()` method to work correctly with the rank-0 blocksparse tensors. This is not super important, but would be nice to have for consistency. Thanks.

**Comment by mganahl** [comment]
thanks for reminding me, I'll fix it.

**Comment by mganahl** [comment]
was already fixed in a previous PR and should work now
