### ISSUE TITLE
Blocksparse REPL problems

### ISSUE THREAD

**Issue by gevenbly** [google/TensorNetwork#616]
Hi @mganahl , there appears to be some issues with the REPL w.r.t the Index class. For instance if I define:
```
i0 = Index(U1Charge([-1,1]), flow=False)
```
Then if I either evaluate `i0` in the REPL or try to `print(i0)` the return is simply `2`. So it appears that the REPL is set to return `i0.dim` when called, but I found this to be very confusing (I thought that I had made a mistake somewhere, and that `i0` was assigned to the integer value 2). Maybe this is not such a big deal if the Index class is going to be removed or hidden from the user, as we discussed could be an option.

Also, on a related note, it would be a great help if the REPL and print() for blocksparse tensors was more informative. At the moment only the class name is returned, but it would be useful to see the rank of the tensor, the dimension of its indices, its flows, its symmetry group(s) etc.

**Comment by mganahl** [comment]
@gevenbly I'll add this quickly
