### ISSUE TITLE
Tensor types and backends

### ISSUE THREAD

**Issue by stavros11** [google/TensorNetwork#66]
If we would like to have the same main network tests (like `tensornetwork_test.py`) for different backends, all based on `np.testing.assert_allclose`, then it might be useful to have a backend method for `get_tensor`. This should return a numpy array for all backends, something like the inverse of `convert_to_tensor` that we already have. It might be tricky to do for TF graph mode where it is a bit harder to go from tensor to numpy, so we will probably need different tests for this case (as we have now). A `get_shape` method would also be handy for the same reason, as @Thenerdstation already mentioned.

**Comment by Thenerdstation** [comment]
Agreed, I think `to_numpy` would useful.

I've tested `assert_allclose` for both Pytorch and eager TF and they work without any conversion, so I think we will be ok.

**Comment by Thenerdstation** [comment]
I think we will implement a `node.shape` property. I also think we should deprecate `get_tensor` and just implement a `node.tensor` property.

**Comment by Thenerdstation** [comment]
https://github.com/google/TensorNetwork/pull/68 does this. All test are run against numpy, tensorflow, and jax.
