### ISSUE TITLE
contractors.optimal is very slow

### ISSUE THREAD

**Issue by gevenbly** [google/TensorNetwork#663]
I was testing the `contractors.optimal` routine for a medium sized network containing 12 tensors (related to a 1D MERA algorithm) and found it to be painfully slow, taking 5hrs+ to produce the optimal order whereas other established algorithms (such as that of arXiv:1304.6112) can produce a guaranteed optimal contraction order for the same network in 0.1secs.

While the other routines such as `contractors.branch` work much faster, they are not guaranteed to be optimal (as far as I can see from reading the opt_einsum documentation), and having a guarantee of optimality is very important in serious calculations.

Maybe it is a good time to overhaul the contractors to move away from opt_einsum, given that they do not seem to be sufficient? Other related issues #175 and #186 could also be addressed during such an overhaul.

**Comment by Thenerdstation** [comment]
Alternatively, these functions could be added to `opt_einsum` and incorporated into our library.

**Comment by gevenbly** [comment]
We could try this option, although I think it would be preferable to have our own internal version, such that it could be configured and modified as we like. In general, the best heuristics for finding optimal or near-optimal contraction orders can depend on the type of network one is solving; if we had a custom solver then it could be tuned to the specific types of network that users of tensornetwork are likely to deal with.

**Comment by Thenerdstation** [comment]
Agreed, I think that sounds like a good idea.

Instead of nuking our use of `opt_einsum`, I'm more in favor of just extending the algorithms we have. Which one we finally call "optimal" I'll leave open for debate.

**Comment by gevenbly** [comment]
Hi @Thenerdstation , I have written some new solvers to find optimal (or near-optimal) contraction orders. Some benchmark results confirm my initial complaint that `opt_einsum` is wildly inefficient. In the case of some test networks of `N` tensors, `opt_einsum` called from the `contractors.branch`, which searches for a good (though not necessarily optimal) contraction has solving time : 

- N=10 requires t=2s
- N=11 requires t=20s
- N=12 requires t=221s

While the `opt_einsum` called from the `contractors.optimal`, which produces a guaranteed optimal path has solving time:

- N=10 requires t=1.7s
- N=11 requires t=17s
- N=12 requires t=194s 

The new routines that I have written can produce a guaranteed optimal path for the same networks with solving time:

- N=10 requires t=0.023s
- N=11 requires t=0.035s
- N=12 requires t=0.045s

Given just how poorly `opt_einsum` performs, I think it should probably be nuked once the new routines are in place and working. As far as the API for calling the solver, I have currently only written an interface between the `ncon` syntax and the solver, such that the solver is called as follows: 
```
# define a network in ncon syntax
chi = 4;
chi_p = 3;
A = np.random.rand(chi,chi,chi,chi)
B = np.random.rand(chi,chi_p,chi_p)
tensors = [A,A,A,A,A,A,A,A,A,A,B]
connects = [[-1,-2,1,2],[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10],
            [9,10,11,12],[11,12,13,14],[13,14,15,16],[15,16,17,18],
            [17,18,19,-3],[19,-4,-5]]

# solve for optimal contraction order
cont_order, costs, is_optimal = ncon_solver(tensors,connects,max_kept=None)

# contract network using optimal order
T = ncon(tensors,connects,cont_order)
```
This API also addresses #175 and #186, for allowing reuse of contraction paths and determination of the contraction `costs`.  Here `max_kept` is an optional argument that can bound the number of contraction paths to check as to reduce the search time (while setting `max_kept=None` checks all valid paths to produce the guaranteed optimal order). Do you have any comments or suggestions for change to this API? (input from @mganahl and @alewis would also be appreciated)

It would also be relatively easy to write an interface between the node/edge formalism and this new network solver, do you know what you want this to look like? In #175 you say that you are thinking of changing the current API to allow reuse of contraction paths.

**Comment by Thenerdstation** [comment]
This sounds good to me. One of the awesome advantages of making the `ncon` API not depend upon `Node`s is that we can now use it within the `contractors`, so I don't see any issues with it.

**Comment by Thenerdstation** [comment]
I would highly encourage you to submit a PR of the work you have for this. We can discuss/change the API at that time, though from your current setup it looks like I would mostly agree with the construction +- some name changing.

**Comment by jcmgray** [comment]
Thought I'd just pop up and say that that the ``optimal`` and ``branch`` algorithms are indeed outdated and not really recommended from ``opt_einsum`` for more than a few tensors (at least by me - and I wrote them!). Instead you might want to compare to the [``dynamic_programming`` optimizer](https://optimized-einsum.readthedocs.io/en/stable/dp_path.html) (``optimize='dp'``) which is essentially still optimal (modulo checking paths with outer products).

**Comment by gevenbly** [comment]
@jcmgray Thanks for letting us know; indeed the `optimize=dp` option does perform much better for the types of network that we commonly encounter. (Incidentally, the authors of the DP paper that you reference are all research collaborators)

**Comment by jcmgray** [comment]
@gevenbly Indeed yeah it's a nice algorithm, and the implementation in ``opt_einsum`` I think is very nice too ([which I can't take credit for](https://github.com/dgasmith/opt_einsum/pull/102)). I just wanted to point out:

1. it pretty much makes ``'optimal'`` and ``branch-*`` algorithms redundant (just takes effort to smoothly factor these things out)
2. my instinct is that it would be hard to do better in pure python, if someone (e.g. you!) implements/compares a faster optimal path finder that would obviously be of interest! 

I'm mainly interested in optimizing things with 100s-1000s of tensors, but even in this case calls to `dp` (on subtrees) still end up being a major bottleneck.

**Comment by Thenerdstation** [comment]
In that case, should we have `optimal` call this DP method instead? I see no reason why we shouldn't.

**Comment by jcmgray** [comment]
> In that case, should we have optimal call this DP method instead? I see no reason why we shouldn't.

My suggestion would be to replace any calls to ``optimal`` and ``branch-all`` by it for sure. I'd like to eventually point ``opt_einsum.paths.optimal`` to it as well and clarify the docs a bit. 

``'dp'`` is also used by default (for up to 16 tensors I think) by the ``'auto-hq'`` method, which may incorporate other improvements as time goes by.

**Comment by mganahl** [comment]
@gevenbly are you OK with closing this?

**Comment by gevenbly** [comment]
Sure, no problem.
