### ISSUE TITLE
Diag considered harmful

### ISSUE THREAD

**Issue by alewis** [google/TensorNetwork#692]
While writing linalg operations I face the question of how to handle the various numpy functions concerning matrix/tensor diagonals. The three in question are:

- `diagonal(data, offset, axis1, axis2)`, which extracts the `offset`'th diagonal from the matrix slice of `data` specified by the axis arguments.

- `diagflat(data, k)`, which flattens `data` and places it in the `k`'th diagonal of a new matrix of zeros.

- `diag(data, k)`, which acts like `diagonal` if data is a matrix and like `diagflat` if it is a vector.

In my opinion `diag` is entirely redundant and too specialized to a matrix-vector setting for our purposes. More importantly, the fact that it does two completely different things depending on the specific shape of `data` is a source of bugs, which I've run into in practice. It's hard to imagine a scenario where a user would actually want a specific line to oscillate between the `diagonal` and `diagflat` behaviour depending on input shape, but quite easy to imagine one where a user forgot they had flattened their tensor and ended up doing the opposite thing they hoped for. 

I therefore propose we support only the former two functions. It's true that this breaks from NumPy somewhat, but NumPy itself only includes this function to maintain equivalence with Matlab. How long will we keep paying for MathWorks' sins?

@mganahl @Thenerdstation @gevenbly

**Comment by mganahl** [comment]
SGTM, `diagonal` and `diagflat` are sufficient.

**Comment by gevenbly** [comment]
@alewis I understand your reasoning entirely, although I personally quite like `diag` as is convenient for operations on diagonal matrices. For instance, if I have a diagonal matrix `S` of singular values then I will often have to construct the inverse:
``` python
S_inv = diag(1 / diag(S))
```
Having a single function `diag` that both extracts and then recasts the diagonal elements is easier to work with (and there are several other use cases for operations on diagonal matrices). However, it is not such a big deal to separate into two distinct functions, so I am in favor that you proceed with your proposal.
