### ISSUE TITLE
TF's graph optimizer could be smarter about transpositions

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#70]
TF is not very smart about transpositions. For example, the graph optimizer could do the following:
1. Merge adjacent transpositions (each transpose op costs time and creates a new tensor)
2. Pull transpositions through reshapes where possible (transposing with fewer dimensions should be faster, and is currently often *much* see #32)
3. Merge transpose ops with matmul ops where possible (turn a matrix transpose into a transpose argument in matmul)

Currently, none of these appear to happen.

TF issue: https://github.com/tensorflow/tensorflow/issues/28933

**Comment by Thenerdstation** [comment]
Yeah, that's not too surprising. Most ML use cases rarely have 10,000x transposes (like we have). 

I really recommend looking into using JAX. https://github.com/google/jax. The compile times are much faster (>5x faster). and the runtime is nearly the same after their most recent release.

**Comment by Thenerdstation** [comment]
JAX support is in as of the latest PR. 

To use it, you can either do `tensornetwork.set_default_backed("jax")` to globally set the backend or do `tensornetwork.TensorNetwork(backend="jax")` for network specific backends.

**Comment by amilsted** [comment]
I wonder if JAX is better at eliminating unnecessary transpositions... I'm more concerned about run times than compile times!

**Comment by Thenerdstation** [comment]
There is a specific op for tensordot in XLA (which JAX uses for {CPT}PU and tensorflow only uses for TPU), so I would expect it to be better by default. If not, the people building it are super nice and crazy supportive. They once fixed 2 bugs I raised in 10 minutes.

https://github.com/google/jax/issues/740
https://github.com/google/jax/issues/738

They are also very supportive of trying to become the default tool for scientists doing experiments. At minimum we should atleast explore it (especially since we already have support for it).

**Comment by amilsted** [comment]
Sounds good! Will give JAX a try at some point. From a look at the source, it seems their tensordot always does transpositions, much like TF's, so this will depend on whether the XLA compiler is smart enough to eliminate them.

**Comment by Thenerdstation** [comment]
We can also fix that. They love getting PRs and are significantly more responsive than the TF team. (mostly because its a much smaller project).

**Comment by jekbradbury** [comment]
If you put tensordots (or other contractions) in a function under `@jit`, the XLA compiler will eliminate redundant transposes and fold the remaining ones into the multiplies.

**Comment by amilsted** [comment]
> If you put tensordots (or other contractions) in a function under `@jit`, the XLA compiler will eliminate redundant transposes and fold the remaining ones into the multiplies.

Hey, that's great!
