### ISSUE TITLE
TF backend should avoid unneeded shape-related ops

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#71]
Methods like `flatten_edges` currently manipulate tensor shapes via `tf.shape()` and other TF ops acting on the resulting tensors. 

Each TF tensor or op increases the run-time overhead in eager mode and increases the graph build and optimization time in graph mode. Fortunately, these shape-related ops can be avoided when the shapes of the tensors involved are fully defined, which is always true in eager mode and is often true when building a graph.

For reference: Within TF, ops like `tensordot` and `einsum` go to some lengths to do these optimizations.

**Comment by Thenerdstation** [comment]
Yeah that's a good idea. 

This might be more difficult with the `backend` abstraction. both `backend.shape` and `backend.prod` would need to be modified to handle dealing with both normal python lists and `tf.Tensor`.

speaking of which, both `prod`, and `concat` are only ever used for shape calculations. If we rename these to `shape_prod` and `shape_concat`, and then try to avoid calling `tf.*` and use `np.*` instead, I think that will be best.
