### ISSUE TITLE
Numpy calls in non-numpy backends

### ISSUE THREAD

**Issue by alewis** [google/TensorNetwork#712]
A few functions in various backends seem to call the numpy equivalent for some reason - an example is sum. Is this intended? I am changing it in my current edit.

**Comment by Thenerdstation** [comment]
All of the `shape` functions do for certain backends. I believe sum was an oversite.

**Comment by alewis** [comment]
Ok, I'll fix sum and leave the ones that operate on shapes alone.

**Comment by mganahl** [comment]
Thanks Adam, yes the jax-backend erroneously calls np.sum, this should be jnp.sum

**Comment by mganahl** [comment]
@alewis is this fixed?

**Comment by alewis** [comment]
Yeah, should be fine to close.
