### ISSUE TITLE
Create Shell Backend

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#72]
Create a shell backend for "ShellTensors" that only store their shape.

**Comment by stavros11** [comment]
I would be interested in looking into this and/or #75. I guess the plan is to have the current `BaseBackend` as a reference and replace all its methods by "shape methods". Perhaps we might need to modify that later depending on the needs of the ContractionNetwork. Let me know if you have any other ideas.

**Comment by Thenerdstation** [comment]
Great!

I would recommend doing this first as #75 will require this.
