### ISSUE TITLE
Add "signature" to nodes. 

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#74]
Give nodes a unique "signature". This is required to easily map nodes in the TensorNetwork to nodes in the ContractionTree. 

For the signature, we can likely reuse the node increment number. We will also have to add a dictionary where we can lookup a node from it's signature for fast runtime.

**Comment by kshithijiyer** [comment]
Do you have a design in mind for this?

**Comment by Thenerdstation** [comment]
Yes, and we've already implemented this on the greed_contractor branch.

**Comment by kshithijiyer** [comment]
Okay. I am interested in this how can I help?

**Comment by Thenerdstation** [comment]
If you want something to help with, look for our "help wanted" issues.

**Comment by viathor** [comment]
I imagine the signatures added in #111 fit the bill here?
