### ISSUE TITLE
add dynamic programming contractor of opt_einsum

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#743]
We should update this asap

**Comment by Thenerdstation** [comment]
Yes we should.

Should we just change the `contractors.optimal` to use `optimize='dp'`? Or should we add a `tn.contractors.dp` method? I'm ok with either, with slight preference to the former.

**Comment by mganahl** [comment]
I think the first choice is better, since it seems that 'dp' is destined to become the new standard in this case anyway at some point.
