### ISSUE TITLE
__add__, __sub__, __truediv__ ... for Node need to be fixed

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#758]
The behaviour of these methods is very unintuitive and unsatisfactory:
```python
node = tn.Node(np.array([1,2,3], dtype=np.float64),backend='tensorflow')
node + 10 #raises an error
```

while this works fine in `tensorflow`:
```python
tensor = tf.convert_to_tensor(np.array([1,2,3], dtype=np.float64))
tensor + 10 #fine
tensor = tf.convert_to_tensor(np.array([1,2,3], dtype=np.float32))
tensor + 10 #fine
```

This is also related to the broken build (#753)

**Comment by manav28** [comment]
Is this issue solved? While using the terminal, I am getting an error as mentioned but when I run it using a separate python file in the same directory as ```network_components.py```, it runs without issues.

**Terminal**
```
>>> import tensornetwork as tn
>>> import numpy as np
>>> node = tn.Node(np.array([1,2,3], dtype=np.float32),backend='tensorflow')
>>> node + 10  # Fails
>>> node + 10. # Passes
```
**File**
```
import numpy as np
from network_components import Node

node = Node(np.array([1,2,3], dtype=np.float64),backend='tensorflow')

new_node = node + 10
print(new_node.tensor) # Passes

new_node = node + 10.
print(new_node.tensor) # Passes
```
I didn't see any difference in the ```__add__``` method of the the package I installed using pip and master.

**Comment by mganahl** [comment]
Hi @manav28 thanks for submitting an issue! 
This bug should be fixed, but it has not been released yet. I tried both codes above and they work.
I'm not sure as to why you don't see any differences in the latest release and the current master though.
Have you tried to fetch and pull the repo?

**Comment by manav28** [comment]
@mganahl False alarm. Something probably went wrong on my local and I got a fresh copy. Now I do see differences. Thanks for the response!

**Comment by mganahl** [comment]
no problem, thanks again for submitting an issue!

**Comment by Thenerdstation** [comment]
If you use it I can push and new version soon.

**Comment by manav28** [comment]
@Thenerdstation No worries. I wanted to contribute on this one. I wanted to verify if it was solved and clarify my question. Thank you for the support.
