### ISSUE TITLE
A quantum number object contains set of "quantum numbers"

### ISSUE THREAD

**Issue by huangrzh** [google/TensorNetwork#761]
I think it is good to generalize the concept of quantum numbers. Sometimes we may have two or several independent charges, for example, a Z2 parity and particle number. So I think it would be very helpful to add some functions as Q(Qa, Qb) derived from two or several different and independent quantum numbers.

**Comment by mganahl** [comment]
thanks @huangrzh for the issue! Is this related to block-sparse tensors, i.e. tensors with a certain symmetry? Our block-sparse backend already allows you to have several independent symmetries. You can for example use the `@` operator to take the direct product of two charge-types
```python 
u1 = U1Charge.random(10,-2,2)
u2 = U1Charge.random(10,-2,2)
u12 = u1 @ u1
print(u12) #u12 corresponds to two independently conserved U1-charges
```

**Comment by huangrzh** [comment]
> thanks @huangrzh for the issue! Is this related to block-sparse tensors, i.e. tensors with a certain symmetry? Our block-sparse backend already allows you to have several independent symmetries. You can for example use the `@` operator to take the direct product of two charge-types
> 
> ```python
> u1 = U1Charge.random(10,-2,2)
> u2 = U1Charge.random(10,-2,2)
> u12 = u1 @ u1
> print(u12) #u12 corresponds to two independently conserved U1-charges
> ```

Thanks @mganahl! This is exactly what I expected.

**Comment by Thenerdstation** [comment]
Is this documented somewhere?

**Comment by mganahl** [comment]
Not yet. I'll rewrite the documentation and I'll add it then
