### ISSUE TITLE
latest pylint break build

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#791]

**Comment by Thenerdstation** [comment]
Can you hardcode the versions that pass?

**Comment by mganahl** [comment]
do you mean hard code into travis requirements?

**Comment by Thenerdstation** [comment]
Yes

**Comment by mganahl** [comment]
it actually looks like older versions of pytype also raise a single error on master right now, at least in python3.8 on my machine (the error it raises should actually be raised, so don't know how this got into master ...)
the last pylint version that passes is 2.5.3

**Comment by mganahl** [comment]
current pytype is actually passing

**Comment by mganahl** [comment]
I think it would make more sense to make the code compatible with latest pytype and pylint versions (see #790), and then add python3.8 support.
