### ISSUE TITLE
import ncon_solver at contractors level

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#795]
Currently it's not imported in the `__init__.py`

**Comment by adityasharma3** [comment]
Hey,
can I take up this issue?

**Comment by mganahl** [comment]
Of course, PRs are always welcome!

**Comment by kaushikroychowdhury** [comment]
I want to work on this. How to start can you guide. I am new to contribution.
Thank you .

**Comment by kaushikroychowdhury** [comment]
What is contractors level ?

**Comment by alewis** [comment]
I think this is fixed? I see ncon_solver in the contractors __init__.py

**Comment by mganahl** [comment]
yes it is! thanks!
