### ISSUE TITLE
add restarted lanczos to JAX backend

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#804]

**Comment by alewis** [comment]
Explicit restarts is pretty easy - in this case it's probably ok to use a plain old for loop. Is that sufficient do you think?

**Comment by mganahl** [comment]
I actually had an implicit restart in mind.

**Comment by alewis** [comment]
Fair enough. But, didn't you do that already? Or was it just Arnoldi?

**Comment by mganahl** [comment]
just arnoldi. BTW implicit arnoldi needs a reworking as well, it's not yet fully jitted
