### ISSUE TITLE
Parallelized edge contraction

### ISSUE THREAD

**Issue by stavros11** [google/TensorNetwork#81]
This might be related to the `ContractionNetwork` issues: It would be good to have a method that allows to contract edges in parallel. 

For example, assume we want to multiply pairs of matrices in a chain:
```
mat = np.random.random([1000, 20, 20])
result = tf.stack([tf.matmul(mat[i], mat[i + 1]) for i in range(0, 1000, 2)])
```
to get a `(500, 20, 20)` tensor. Doing `result = tf.matmul(mat[::2], mat[1::2])` is ~x10 faster. The API would be something like `net.parallelized_contract([list of edges])` .

**Comment by Thenerdstation** [comment]
So your case of 10x speedup is very specific to this setup (most parallel edge contractions can't be easily reduced to a simple `matmul`). I'm pretty sure JAX and TF both parallelize as much as possible in `@tf.function` and `@jax.jit` modes, so I'm not sure what else we could do on our side.

Beyond that, doing parallel contraction of arbitrary edges will require knowing the optimal contraction order, which requires a smart contraction algorithm. All of which will be handled with `ContractionNetwork` and `net.async_contraction`

I think most of your wants are going to be fulfilled with the `ContractioNetwork`. If you have a specific design in mind that I'm not seeing, feel free to reopen this issue.
