### ISSUE TITLE
default param in GMRES

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#812]
the current default for `num_krylov_vectors` is `b.size`. This means one defaults to building the entire vector space, which seems rather unpractical for a sparse solver. @alewis any thoughts?

**Comment by alewis** [comment]
We can change it to the NumPy default if you like - since the present
implementation halts the Arnoldi process early if convergence is reached
it's less problematic than it may seem, but you're probably right.

**Comment by mganahl** [comment]
I haven't tested it extensively, but I was wondering about ill-conditioned problems, where gmres would essentially freeze if the ncv was say 10**6
