### ISSUE TITLE
merge ncon versions

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#815]
We currently support two different versions of `ncon`, one taht works only for `tn.Tensor` (`tn.linalg.operations.ncon`)
and one that works for backend arrays and `Node` (`tn.ncon_interface.ncon`, also imported at top level as `tn.ncon`). 
I propose to have `tn.ncon` work on `Tensor` and `Node` only

**Comment by Thenerdstation** [comment]
I'd propose only supporting backend arrays and `Tensor`. Supporting `Node` always felt awkward

**Comment by mganahl** [comment]
SGTM, I'll fix this!
