### ISSUE TITLE
TensorNetwork.kron does not work correctly

### ISSUE THREAD

**Issue by YijianZou** [google/TensorNetwork#816]
TensorNetwork.kron is not what kron works in the usual way. 
kron(A,B) should be equivalent to ncon([A,B],[[-1,-3],[-2,-4]]) but it does not work out this way.

**Comment by Thenerdstation** [comment]
Can you give a repo code? You're right those two should be equal.

**Comment by YijianZou** [comment]
I am not sure whether I understand your question. Are you asking for the source code of kron in the repository or are you asking for an instance that the kron method goes wrong?

**Comment by Thenerdstation** [comment]
> asking for an instance that the kron method goes wrong?

That one

**Comment by Thenerdstation** [comment]
The main reason I ask is to see how you use kron.

**Comment by YijianZou** [comment]
import numpy as np
import TensorNetwork as tn
from TensorNetwork.linalg.operations import ncon
X=tn.Tensor(np.array([[0.0,1.0],[1.0,0.0]]))
Id=tn.Tensor(np.eye(3))

XI_kron=kron(X,Id)
XI_ncon=ncon([X,Id],[[-1,-3],[-2,-4]])

print(XI_kron.array.shape)  #This one has shape (2,2,3,3)
print(XI_ncon.array.shape)  #This one has shape (2,3,2,3)

print(XI_kron.array[0,1,:,:])  # I don't know how this result comes about
print(XI_ncon.array[0,:,1,:]) #This gives eye(3), the correct one

**Comment by mganahl** [comment]
yes, that's a bug. Thanks Yijian!
