### ISSUE TITLE
Support ones_like and zeros_like as Tensor initialization methods

### ISSUE THREAD

**Issue by alewis** [google/TensorNetwork#842]

**Comment by MikeMerz** [comment]
Hey, Im new to contributing , mind if I try this one?

**Comment by alewis** [comment]
Sure, that'd be great!

The Tensor initialization methods are in `tensornetwork/linalg/initialization.py`, which is also where these should go. Tests go in `tensornetwork/linalg/tests`.

**Comment by MikeMerz** [comment]
Just to clarify , the input object has to be array-like(numpy, array, tensornetwork) right?

**Comment by alewis** [comment]
It's a good question. I think it's probably ok to allow the input object to be any array type, yeah.

In the case that the input object is itself a Tensor, this function should create a new Tensor of zeros (ones) with the same shape, dtype, and backend.

In the case that the input object is a backend array, the user should also specify the backend, and the function should return a new Tensor of zeros (ones) with the same shape, the specified backend, and the equivalent dtype in that backend. 

You can achieve this using `backend.convert_to_tensor`

**Comment by mganahl** [comment]
Hi! Thanks @MikeMerz for contributing! The input array should either be an `np.ndarray` or a backend array. `convert_to_tensor` will do that for you, i.e. convert a `np.ndarray` to a backend array, or throw an error if the input array does not match the backend.

**Comment by MikeMerz** [comment]
Ok , in case convert_to_tensor rasises an exception would you like to raise the same exception or a different informative massage?
By the way , while running my tests, during the pytorch part a Type exception is raised about torch.float32 by convert_to_tensor,any idea why this spesific type causes the excption?

**Comment by alewis** [comment]
Hi @MikeMerz,

Sorry for the mixed messages - I think the input array (to `ones_like` or `zeros_like`), should also be allowed to be a `Tensor`, in addition to the above. 

As for the type exception it's hard to say exactly without seeing the code that causes the error. Could you append a snippet, or ideally link to a Colab that reproduces the error?

**Comment by MikeMerz** [comment]
Hi @alewis,
To summarize we'll get:
1)type is np.ndarray - call convert_to_tensor to change to a backend and init with the arrays shape and given backend and type?
2)type is backend - DO NOT call convert_to_tensor and continue as above
3) typse is Tensor - we just init a new one and the same attributes
Did I get it right?
I think the error derives from an err in the above.

**Comment by alewis** [comment]
Right so we want (in my opinion):

Type is np.ndarray or Tensor should behave as you say.

When I say a backend array I mean the array type of one of the backends; e.g. a numpy array, PyTorch Tensor, etc. The np.ndarray is a special case of this; thus, one should again call convert_to_tensor to change to the specified backend, which might differ from that of the given array.

As for the backend itself, there should be the following possibilities:
1) backend is None: retrieve the default backend
2) backend is a string: retrieve the backend specified by the string, or else throw ValueError if the string is wrong.
3) backend is a backend object: use that object.

**Comment by MikeMerz** [comment]
OK, it seems the only question I have left is  that for the backend input, it seems that it doesn't have a shape so a default shape of (1,1,1) would suffice?

**Comment by alewis** [comment]
The argument named `backend` is not an array, but a specification of the
backend to be operated on. It may be specified in three valid ways:

1. backend = None -> retrieves the default backend, which is set by a
global flag. Check one of the other functions for details of how to handle
this.

2. backend = string -> generates a backend object from this string, and
uses the result.

3. backend = (backend type) -> uses the given backend.

The "backend type" is an instance of the class defined in
tensornetwork/backends/abstract_backend.py. The concrete subclasses are
defined in the subfolders.

**Comment by alewis** [comment]
Well, we'll sort it out in the PR. So yeah go for it!

**Comment by alewis** [comment]
Addressed successfully by @MikeMerz!
