### ISSUE TITLE
Disabling initial Normalization of MPS tensors

### ISSUE THREAD

**Issue by skothegh** [google/TensorNetwork#882]
Hello,

is it somehow possible to disable the automatic normalization of the tensors of the MPS?

I require the MPS to be initialized with tensors whose first and last element sum to 1, and the initial normalization messes with that. 

What I have is the following:

```
import numpy as np
import tensornetwork as tn

p1 = np.zeros([1,4,1])
p1[0][0][0] = 0.5
p1[0][3][0] = 0.5

mps = tn.FiniteMPS([p1,p1])

print(mps.get_tensor(0))
## this yields:
## array([[[-0.70710678],
##       [0],
##       [0.],
##       [-0.70710678]]])

```
I would like to get 
 array([[[0.5], [0],[ 0. ],[0.5]]])
Is that somehow possible?

Best regards,
Sk

**Comment by mganahl** [comment]
you can use `canonicalize=False` in the initialization:
```python 
import numpy as np
import tensornetwork as tn

p1 = np.zeros([1,4,1])
p1[0][0][0] = 0.5
p1[0][3][0] = 0.5

mps = tn.FiniteMPS([p1,p1],canonicalize=False)

print(mps.get_tensor(0))

```

**Comment by skothegh** [comment]
Thank you kindly! That is exactly what I have been looking for. I must have overlooked that option a good dozen times. 

Best regards!
