### ISSUE TITLE
get rid of Travis

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#883]
the travis build gets stuck quite often. We should move it to somewhere else

**Comment by alewis** [comment]
What do you mean, somewhere else?

**Comment by alewis** [comment]
I mean, we need a build system. What would we do instead?

**Comment by mganahl** [comment]
Git actions for example
Adam Lewis <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 16:34:

**Comment by mganahl** [comment]
I will setup a workflow using Actions. We can keep the Travis build as well for now, and phase it our later.
