### ISSUE TITLE
tn.reachable breaks when given tuples containing edges

### ISSUE THREAD

**Issue by jemisjoky** [google/TensorNetwork#897]
Here's a minimal working example to show what goes wrong:

```python
import numpy as np
import tensornetwork as tn

node = tn.Node(np.eye(2))
edge_tuple = (node[0], node[1])
reachable_nodes = tn.reachable(edge_tuple)
```

Everything works fine when I use a list for edges, and it appears the issue is `tn.reachable` assuming that any list-like collection of edges is necessarily a list. Should be an easy fix, thanks :)

**Comment by mganahl** [comment]
thanks @jemisjoky, should be fixed by today
