### ISSUE TITLE
Should ncon allow "0" as a label?

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#90]
I skimmed the [NCON paper](https://arxiv.org/abs/1402.0939) the other day and realized why other implementations tend to disallow `0` as a label for contraction edges: It is because the reference implementation of NCON treats `0` specially - it is used as part of a separate contraction order argument to specify when to carry out outer products (sometimes it is more efficient to do outer products as intermediate steps). This raised two issues for me:

1. Should we stop accepting `0` as a valid contraction edge label to ensure our ncon calls are compatible with the reference implementation? (Probably yes...)
2. Should we implement the (rather obscure) interpretation of `0` in the contraction order? (Probably no.)

Elaborating on 2: It's a lot of work for possibly very little gain. Instead just support using a specific smart contractor, or a saved contraction order, in `ncon()`: e.g. `ncon(..., contractor='optimal')`.

Thoughts?

**Comment by mganahl** [comment]
1: Either way is fine with me. 2: probably no (I never used it so far)

**Comment by Thenerdstation** [comment]
I guess my preference is to keep ncon consistent with the original interface.

For now, throw a `NotImplementedError` and maybe set this issue as a "Help wanted".

**Comment by Thenerdstation** [comment]
Close this? I don't think we will be supporting 0 in the future.

**Comment by amilsted** [comment]
Yeah.
