### ISSUE TITLE
Implement a Greedy contractor

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#91]
Implement a contractor that will deterministically do the lowest cost `contract_between` call possible.

Ideally, it would also keep track of the lowest cost pairs in a heap, so that the runtime is nlog(n) instead of n^2.

**Comment by Thenerdstation** [comment]
One of the issues I'm hitting right now is the deterministic aspect. Currently, if two pairs of nodes have the same cost, then the order of which they get contracted is not deterministic. 

I think the best way around this is to add a "signature" to the nodes. This value will come from the `node_increment` we already are using. This will add another parameter to the `Node` constructor, but I think that will be ok.

**Comment by mganahl** [comment]
Hey @Thenerdstation, I'd be interested to help with this. Do you have a particular contraction algorithm for the full contraction in your mind already? There is a paper describing some optimized0 BF or DF search algorithms that we could implement

**Comment by Thenerdstation** [comment]
I will likely have this one done today, but I would love to have a backtracking algorithm using BF or DF search. Feel free to make another issue and assign yourself to it.
