### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by skothegh** [google/TensorNetwork#910]
Hello,
I just installed TN on a second laptop using "pip3 install tensornetwork". It seemed to have installed everything fine, but when I import tensornetwork, it tells me "module not found". 
As for my python installations: I first installed pip3, Anaconda, and then TN. Am I missing some libraries? I cannot remember doing anything else on the old machine.

**Comment by mganahl** [comment]
it works on my laptop. Seems like an issue with your python installation. did you install inside a venv? If so maybe restart it.

**Comment by skothegh** [comment]
Haven't tried the trusty old restart method, yet! What is a venv?

**Comment by skothegh** [comment]
Haven't tried the trusty old restart method, yet! What is a venv?

**Comment by mganahl** [comment]
it's a virtual environment. venvs help you separating different python setups from each other by generating encapsulated environments that do not know of each other (conda also uses virtual environments as well). This way you can't e.g. mess up your systemwide python installation by installing conflicting packages. 

maybe try this in your terminal

```shell
$python3.9 -m venv tn_venv #or whichever python3 version you are using
$source tn_env/bin/activate
$pip install --upgrade pip tensornetwork
```
now if you fire up an interpreter it should work:
```shell
$python3.9
>>>import tensornetwork as tn
```

**Comment by skothegh** [comment]
Oof. I will look into that.

**Comment by skothegh** [comment]
The problem was that I used pip3 install python. For some reason it works when I use pip.
