### ISSUE TITLE
Tensorized GRU/LSTM for tensorflow

### ISSUE THREAD

**Issue by timechild666** [google/TensorNetwork#921]
Any plans for adding tensorized rnn architectures here? Such as Tensor-Train GRU/LSTM.

Basically like this here https://github.com/onucharles/tensorized-rnn but for tensorflow/tensornetwork.

Thanks for advance
Martin

**Comment by mganahl** [comment]
Hi @timechild666, sorry for the very late reply! The work above is very interesting, but adding this to the repository seems a bit out of scope. If you plan to use tensornetwork to build something along these lines we'd be curious to hear about it tho!
