### ISSUE TITLE
Flaky Test when seed not used

### ISSUE THREAD

**Issue by crawlingcub** [google/TensorNetwork#943]
The test `test_max_truncation_error` in `tensornetwork/backends/symmetric/decompositions_test.py` [link](https://github.com/google/TensorNetwork/blob/edf3f345640c64595b4ad1002bebf4a008988b3e/tensornetwork/backends/symmetric/decompositions_test.py#L90) almost always fails when the seed [here](https://github.com/google/TensorNetwork/blob/edf3f345640c64595b4ad1002bebf4a008988b3e/tensornetwork/backends/symmetric/decompositions_test.py#L91) is removed. This happens only for `[3-float64]` and `[4-complex128]` parameters. The test failed 500/500 times for me for both these parameters.

From the error message it seems `svals[mask][::-1]` is always empty whereas `S2.data` most often has an element of size 1(except when using the seed). Is this expected? Or is this indicative of a bug?

Please let me know if you need more details. I will be happy to raise a PR if you have any suggestions on how to fix it.

Test failure message:
```
>     np.testing.assert_allclose(S2.data, svals[mask][::-1])
E     AssertionError:
E     Not equal to tolerance rtol=1e-07, atol=0
E
E     (shapes (1,), (0,) mismatch)
E      x: array([1.])
E      y: array([], dtype=float64)

tensornetwork/backends/symmetric/decompositions_test.py:112: AssertionError
```

Environment:
```
Anaconda python 3.6
tensorflow==2.6.0
numpy==1.19.5
scipy==1.5.4
```

**Comment by mganahl** [comment]
@crawlingcub thanks for the message! 

The reason the tests fail is because thesymmetric  svd decomposition behaves a bit strangely: if max_truncation_error is chosen so large that all singular values would be truncated  then instead of truncating all of them it leaves the largest one. 

I'll change it to actually perform the full truncation.

You are mentioning that this happens for test-parameters `[3-float64]` and `[4-complex128]`. The first number here is the number of distinct charge-types. Out of curiosity, did you change the pytest parameters for the tests? In our test we are only going up to 3 distinct charge types.

**Comment by crawlingcub** [comment]
> The reason the tests fail is because thesymmetric svd decomposition behaves a bit strangely: if max_truncation_error is chosen so large that all singular values would be truncated then instead of truncating all of them it leaves the largest one.

I see. Would you then call this a bug in the implementation?

> You are mentioning that this happens for test-parameters `[3-float64]` and `[4-complex128]`. The first number here is the number of distinct charge-types.

My bad, it should be `[3-float64]` and `[3-complex128]`.

Also, do you think that the seed setting can now be removed?

**Comment by crawlingcub** [comment]
I also found some other tests which have similar behavior. I can send them, if you are interested! Thanks!

**Comment by mganahl** [comment]
I wouldn't call it a bug, since this was intentional behaviour. 
In general we prefer to seed tests for ease of reproducability. I changed the test though to run a bunch of different seed values, just to make sure

**Comment by mganahl** [comment]
Feel free to post any other tests or use-cases with similar issues. We can look at them and decide if they need to be updated.
