### ISSUE TITLE
Implement a generic, deterministic contraction-order optimization 

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#95]
We should have at least one method that uses some heuristic approach like pruned BFS or DFS to obtain optimal contraction order sequences for an arbitrary network.

**Comment by mganahl** [comment]
@Thenerdstation I'm interested in working on that. Could you assign me? It seems I can't assign myself

**Comment by Thenerdstation** [comment]
Done. Do you wanna setup a video chat to discuss engineering requirements?

**Comment by mganahl** [comment]
thanks. Yes let's do that. Would someday next week be OK?

**Comment by Thenerdstation** [comment]
Yep! Let's continue this over email.

**Comment by amilsted** [comment]
Should I be worried about trying to do this in python? Seems like a search algorithm for an NP-hard problem should at least not have to suffer from interpreter overhead! Could we use cython, for example?

**Comment by mganahl** [comment]
I talked to a guy at IBM about this, and they use Cpp for it. I think an initial implementation in 
python is fine, but ultimately it should be ported to C/Cpp (or cython)

**Comment by Thenerdstation** [comment]
I agree. Let's do it in this order

Python -> Cython -> C++

We're short on headcount to keep C++ code stable right now, so I'd rather just start with python and upgrade it as usage increases

**Comment by amilsted** [comment]
Sounds good!
