### ISSUE TITLE
Is there a simple way to multiply a scalar to the tensor values of a node that is part of a network of tensors?

### ISSUE THREAD

**Issue by prem314** [google/TensorNetwork#969]
I have a tensor network whose elements are quite large, and I want to rescale the tensor values of the entire network by dividing by a fixed number. How do I do it in a simple manner?

**Comment by mganahl** [comment]
hi! have you tried dividing one of the tensors by this number? alternatively you can divide each tensor by the N-th square root, where N is the number of tensors

**Comment by prem314** [comment]
Hi. Thanks. I had not realized earlier that if one wants to modify the tensor value of any tensor in a network, let us say node1, then all one needs to do is-

node1.tensor = any new numpy array.

Side remark- Interestingly, if one supplies a new tensor of different rank or shape to the node, then the code does not immediately give an error, but will give an error for subsequent calculation, like edge contraction.
